local TXUI, F, E, I, V, P, G = unpack(select(2, ...))
local PF = TXUI:GetModule("Profiles")

local pairs = pairs
local type = type

function PF:ElvUIProfile()
    -- Force disable Information Panel
    for _, v in pairs(E.db.unitframe.units) do
        if type(v) == "table" and type(v.infoPanel) == "table" then v.infoPanel.enable = false end
    end

    -- Movers
    E.db["movers"] = E.db["movers"] or {}
    E.db["movers"]["AlertFrameMover"] = "TOPRIGHT,ElvUIParent,TOPRIGHT,-568,-235"
    E.db["movers"]["ArenaHeaderMover"] = "TOPRIGHT,ElvUIParent,TOPRIGHT,-305,-370"
    E.db["movers"]["AzeriteBarMover"] = "TOP,ElvUIParent,TOP,351,-324"
    E.db["movers"]["BelowMinimapContainerMover"] = "TOPLEFT,ElvUIParent,TOPLEFT,195,-220"
    E.db["movers"]["BNETMover"] = "TOPRIGHT,ElvUIParent,TOPRIGHT,-240,-185"
    E.db["movers"]["BossHeaderMover"] = "BOTTOMRIGHT,ElvUIParent,BOTTOMRIGHT,-303,440"
    E.db["movers"]["BuffsMover"] = "TOPLEFT,ElvUIParent,TOPLEFT,4,-4"
    E.db["movers"]["DebuffsMover"] = "TOPLEFT,ElvUIParent,TOPLEFT,4,-66"
    E.db["movers"]["DTPanelClockMover"] = "TOPRIGHT,ElvUIParent,TOPRIGHT,0,-222"
    E.db["movers"]["DurabilityFrameMover"] = "BOTTOMRIGHT,ElvUIParent,BOTTOMRIGHT,-580,47"
    E.db["movers"]["ElvAB_1"] = "BOTTOM,ElvUIParent,BOTTOM,0,47"
    E.db["movers"]["ElvAB_10"] = "TOPRIGHT,ElvUIParent,TOPRIGHT,-180,-401"
    E.db["movers"]["ElvAB_2"] = "TOPRIGHT,ElvUIParent,TOPRIGHT,-37,-401"
    E.db["movers"]["ElvAB_3"] = "BOTTOM,ElvUIParent,BOTTOM,340,47"
    E.db["movers"]["ElvAB_4"] = "BOTTOM,ElvUIParent,BOTTOM,-340,47"
    E.db["movers"]["ElvAB_5"] = "BOTTOM,ElvUIParent,BOTTOM,195,47"
    E.db["movers"]["ElvAB_6"] = "BOTTOM,ElvUIParent,BOTTOM,-195,47"
    E.db["movers"]["ElvAB_7"] = "TOPRIGHT,ElvUIParent,TOPRIGHT,-73,-401"
    E.db["movers"]["ElvAB_8"] = "TOPRIGHT,ElvUIParent,TOPRIGHT,-109,-401"
    E.db["movers"]["ElvAB_9"] = "TOPRIGHT,ElvUIParent,TOPRIGHT,-144,-401"
    E.db["movers"]["ElvNP_PlayerMover"] = "TOP,UIParent,CENTER,0,-150"
    E.db["movers"]["ElvUF_AssistMover"] = "BOTTOMLEFT,ElvUIParent,BOTTOMLEFT,470,40"
    E.db["movers"]["ElvUF_PetCastbarMover"] = "TOPLEFT,ElvUF_Pet,BOTTOMLEFT,0,-1"
    E.db["movers"]["ElvUF_TankMover"] = "BOTTOMLEFT,ElvUIParent,BOTTOMLEFT,470,105"
    E.db["movers"]["ElvUIBagMover"] = "BOTTOMRIGHT,ElvUIParent,BOTTOMRIGHT,-235,310"
    E.db["movers"]["ElvUIBankMover"] = "BOTTOMLEFT,ElvUIParent,BOTTOMLEFT,250,310"
    E.db["movers"]["ExperienceBarMover"] = "BOTTOM,ElvUIParent,BOTTOM,0,43"
    E.db["movers"]["GMMover"] = "TOPRIGHT,ElvUIParent,TOPRIGHT,-549,-3"
    E.db["movers"]["HonorBarMover"] = "TOPRIGHT,ElvUIParent,TOPRIGHT,-573,-422"
    E.db["movers"]["LeftChatMover"] = "BOTTOMLEFT,ElvUIParent,BOTTOMLEFT,5,60"
    E.db["movers"]["LevelUpBossBannerMover"] = "TOP,ElvUIParent,TOP,0,-170"
    E.db["movers"]["LootFrameMover"] = "TOPRIGHT,ElvUIParent,TOPRIGHT,-398,-465"
    E.db["movers"]["MicrobarMover"] = "BOTTOMLEFT,ElvUIParent,BOTTOMLEFT,495,30"
    E.db["movers"]["MinimapMover"] = "TOPRIGHT,ElvUIParent,TOPRIGHT,-4,-4"
    E.db["movers"]["MirrorTimer1Mover"] = "TOP,ElvUIParent,TOP,-1,-96"
    E.db["movers"]["MirrorTimer2Mover"] = "TOP,MirrorTimer1,BOTTOM,0,0"
    E.db["movers"]["MirrorTimer3Mover"] = "TOP,MirrorTimer2,BOTTOM,0,0"
    E.db["movers"]["ObjectiveFrameMover"] = "TOPRIGHT,ElvUIParent,TOPRIGHT,-70,-270"
    E.db["movers"]["PetBattleABMover"] = "BOTTOMLEFT,ElvUIParent,BOTTOMLEFT,76,313"
    E.db["movers"]["PetBattleStatusMover"] = "TOP,PetBattleFrame,TOP,0,0"
    E.db["movers"]["RaidMarkerBarAnchor"] = "TOPRIGHT,ElvUIParent,TOPRIGHT,-325,-4"
    E.db["movers"]["WTRaidMarkersBarAnchor"] = "BOTTOMLEFT,ElvUIParent,BOTTOMLEFT,5,265"
    E.db["movers"]["RaidUtility_Mover"] = "TOPRIGHT,ElvUIParent,TOPRIGHT,-550,-4"
    E.db["movers"]["ReputationBarMover"] = "TOPRIGHT,ElvUIParent,TOPRIGHT,-3,-264"
    E.db["movers"]["RightChatMover"] = "BOTTOMRIGHT,ElvUIParent,BOTTOMRIGHT,-5,60"
    E.db["movers"]["SocialMenuMover"] = "TOPLEFT,ElvUIParent,TOPLEFT,4,-187"
    E.db["movers"]["TalkingHeadFrameMover"] = "TOP,ElvUIParent,TOP,0,-10"
    E.db["movers"]["ThreatBarMover"] = "TOPRIGHT,ElvUIParent,TOPRIGHT,-554,-363"
    E.db["movers"]["TooltipMover"] = "BOTTOMRIGHT,ElvUIParent,BOTTOMRIGHT,-4,280"
    E.db["movers"]["TopCenterContainerMover"] = "TOPRIGHT,ElvUIParent,TOPRIGHT,-380,-65"
    E.db["movers"]["TotemBarMover"] = "BOTTOM,ElvUIParent,BOTTOM,-333,201"
    E.db["movers"]["UIErrorsFrameMover"] = "TOP,UIParent,TOP,0,-122"
    E.db["movers"]["VehicleLeaveButton"] = "BOTTOMRIGHT,ElvUIParent,BOTTOMRIGHT,-644,47"
    E.db["movers"]["VehicleSeatMover"] = "BOTTOMRIGHT,ElvUIParent,BOTTOMRIGHT,-305,330"
    E.db["movers"]["VOICECHAT"] = "TOPLEFT,ElvUIParent,TOPLEFT,368,-210"

    -- DataBars
    E.db["databars"]["azerite"]["enable"] = false
    E.db["databars"]["experience"]["enable"] = false
    E.db["databars"]["honor"]["enable"] = false
    E.db["databars"]["threat"]["enable"] = false

    -- Tooltip
    E.db["tooltip"]["colorAlpha"] = 0.75
    E.db["tooltip"]["guildRanks"] = false
    E.db["tooltip"]["healthBar"]["font"] = "- Big Noodle Titling"
    E.db["tooltip"]["healthBar"]["fontSize"] = 17
    E.db["tooltip"]["healthBar"]["height"] = 15
    E.db["tooltip"]["playerTitles"] = false
    E.db["tooltip"]["visibility"]["combatOverride"] = "CTRL"

    -- Bags
    E.db["bags"]["bagSize"] = 44
    E.db["bags"]["bagWidth"] = 700
    E.db["bags"]["bankSize"] = 40
    E.db["bags"]["bankWidth"] = 700
    E.db["bags"]["clearSearchOnClose"] = true
    E.db["bags"]["cooldown"]["fonts"]["enable"] = true
    E.db["bags"]["cooldown"]["fonts"]["font"] = "- Steelfish"
    E.db["bags"]["countFont"] = "- Steelfish"
    E.db["bags"]["countFontOutline"] = "OUTLINE"
    E.db["bags"]["countFontSize"] = 24
    E.db["bags"]["itemLevelFont"] = "- Steelfish"
    E.db["bags"]["itemLevelFontOutline"] = "OUTLINE"
    E.db["bags"]["itemLevelFontSize"] = 20
    E.db["bags"]["itemInfoFont"] = "- Steelfish"
    E.db["bags"]["itemInfoFontOutline"] = "OUTLINE"
    E.db["bags"]["itemInfoFontSize"] = 24
    E.db["bags"]["junkIcon"] = true
    E.db["bags"]["moneyCoins"] = false
    E.db["bags"]["scrapIcon"] = true
    E.db["bags"]["showBindType"] = true
    E.db["bags"]["vendorGrays"]["enable"] = true

    -- Chat
    E.db["chat"]["panelColor"]["a"] = 0
    E.db["chat"]["customTimeColor"]["b"] = 0.88627450980392
    E.db["chat"]["customTimeColor"]["g"] = 0.75686274509804
    E.db["chat"]["customTimeColor"]["r"] = 0
    E.db["chat"]["emotionIcons"] = false
    E.db["chat"]["fontSize"] = 16
    E.db["chat"]["hideCopyButton"] = true
    E.db["chat"]["inactivityTimer"] = 15
    E.db["chat"]["keywords"] = "ElvUI, Toxi, %MYNAME%, ToxiUI"
    E.db["chat"]["panelBackdrop"] = "HIDEBOTH"
    E.db["chat"]["panelHeight"] = 200
    E.db["chat"]["panelHeightRight"] = 200
    E.db["chat"]["panelTabBackdrop"] = true
    E.db["chat"]["panelWidth"] = 400
    E.db["chat"]["panelWidthRight"] = 400
    E.db["chat"]["separateSizes"] = true
    E.db["chat"]["tabFont"] = "- Big Noodle Titling"
    E.db["chat"]["tabFontSize"] = 14
    E.db["chat"]["timeStampFormat"] = "%H:%M "
    E.db["chat"]["hideVoiceButtons"] = true

    -- Auras
    E.db["auras"]["buffs"]["countFont"] = "- Steelfish"
    E.db["auras"]["buffs"]["countFontOutline"] = "OUTLINE"
    E.db["auras"]["buffs"]["countFontSize"] = 24
    E.db["auras"]["buffs"]["fadeThreshold"] = 3
    E.db["auras"]["buffs"]["growthDirection"] = "RIGHT_DOWN"
    E.db["auras"]["buffs"]["maxWraps"] = 1
    E.db["auras"]["buffs"]["wrapAfter"] = 18
    E.db["auras"]["buffs"]["size"] = 34
    E.db["auras"]["buffs"]["timeFont"] = "- Big Noodle Titling"
    E.db["auras"]["buffs"]["timeFontOutline"] = "NONE"
    E.db["auras"]["buffs"]["timeFontSize"] = 20
    E.db["auras"]["buffs"]["seperateOwn"] = -1
    E.db["auras"]["debuffs"]["countFont"] = "- Steelfish"
    E.db["auras"]["debuffs"]["countFontOutline"] = "OUTLINE"
    E.db["auras"]["debuffs"]["countFontSize"] = 24
    E.db["auras"]["debuffs"]["growthDirection"] = "RIGHT_DOWN"
    E.db["auras"]["debuffs"]["size"] = 42
    E.db["auras"]["debuffs"]["timeFont"] = "- Big Noodle Titling"
    E.db["auras"]["debuffs"]["timeFontOutline"] = "NONE"
    E.db["auras"]["debuffs"]["timeFontSize"] = 20

    -- UF Colors & Stuff
    E.db["unitframe"]["colors"]["auraBarBuff"]["b"] = 0.2274504750967
    E.db["unitframe"]["colors"]["auraBarBuff"]["g"] = 0.11764679849148
    E.db["unitframe"]["colors"]["auraBarBuff"]["r"] = 0.76862573623657
    E.db["unitframe"]["colors"]["castColor"]["b"] = 0
    E.db["unitframe"]["colors"]["castColor"]["g"] = 0.70196078431373
    E.db["unitframe"]["colors"]["castColor"]["r"] = 1
    E.db["unitframe"]["colors"]["castInterruptedColor"]["b"] = 0.10196078431373
    E.db["unitframe"]["colors"]["castInterruptedColor"]["g"] = 0.10196078431373
    E.db["unitframe"]["colors"]["castInterruptedColor"]["r"] = 1
    E.db["unitframe"]["colors"]["castNoInterrupt"]["b"] = 0.50196078431373
    E.db["unitframe"]["colors"]["castNoInterrupt"]["g"] = 0.50196078431373
    E.db["unitframe"]["colors"]["castNoInterrupt"]["r"] = 0.50196078431373
    E.db["unitframe"]["colors"]["classResources"]["MONK"][6]["b"] = 0.22745098039216
    E.db["unitframe"]["colors"]["classResources"]["MONK"][6]["r"] = 0.047058823529412
    E.db["unitframe"]["colors"]["classbackdrop"] = true
    E.db["unitframe"]["colors"]["colorhealthbyvalue"] = false
    E.db["unitframe"]["colors"]["disconnected"]["b"] = 0.52941176470588
    E.db["unitframe"]["colors"]["disconnected"]["g"] = 0.57647058823529
    E.db["unitframe"]["colors"]["disconnected"]["r"] = 1
    E.db["unitframe"]["colors"]["power"]["FURY"]["b"] = 0.15294117647059
    E.db["unitframe"]["colors"]["power"]["FURY"]["g"] = 0.49411764705882
    E.db["unitframe"]["colors"]["power"]["MANA"]["b"] = 0.8156862745098
    E.db["unitframe"]["colors"]["power"]["MANA"]["g"] = 0.84705882352941
    E.db["unitframe"]["colors"]["power"]["MANA"]["r"] = 0.26274509803922
    E.db["unitframe"]["colors"]["reaction"]["BAD"]["b"] = 0.25098039215686
    E.db["unitframe"]["colors"]["reaction"]["BAD"]["g"] = 0.25098039215686
    E.db["unitframe"]["colors"]["reaction"]["GOOD"]["r"] = 0.29411764705882
    E.db["unitframe"]["colors"]["selection"][0]["b"] = 0.17647058823529
    E.db["unitframe"]["colors"]["selection"][0]["g"] = 0.17647058823529
    E.db["unitframe"]["colors"]["selection"][1]["b"] = 0.19607843137255
    E.db["unitframe"]["colors"]["selection"][2]["b"] = 0.19607843137255
    E.db["unitframe"]["colors"]["selection"][3]["r"] = 0.19607843137255
    E.db["unitframe"]["colors"]["selection"][6]["g"] = 0.19607843137255
    E.db["unitframe"]["colors"]["selection"][7]["g"] = 0.19607843137255
    E.db["unitframe"]["colors"]["selection"][8]["r"] = 0.19607843137255
    E.db["unitframe"]["colors"]["useDeadBackdrop"] = true
    E.db["unitframe"]["colors"]["transparentPower"] = false
    E.db["unitframe"]["colors"]["healPrediction"]["absorbs"]["a"] = 0.5
    E.db["unitframe"]["colors"]["healPrediction"]["absorbs"]["b"] = 0.94509803921569
    E.db["unitframe"]["colors"]["healPrediction"]["absorbs"]["g"] = 0
    E.db["unitframe"]["colors"]["healPrediction"]["overabsorbs"]["a"] = 0.5
    E.db["unitframe"]["colors"]["healPrediction"]["overabsorbs"]["b"] = 0.75686274509804
    E.db["unitframe"]["colors"]["healPrediction"]["overabsorbs"]["g"] = 0
    E.db["unitframe"]["font"] = "- Big Noodle Titling"
    E.db["unitframe"]["fontSize"] = 18
    E.db["unitframe"]["fontOutline"] = "OUTLINE"
    E.db["unitframe"]["smoothbars"] = true
    E.db["unitframe"]["smartRaidFilter"] = false
    E.db["unitframe"]["cooldown"]["fonts"]["enable"] = true
    E.db["unitframe"]["cooldown"]["fonts"]["font"] = "- Steelfish"
    E.db["unitframe"]["cooldown"]["fonts"]["fontSize"] = 26

    -- > Create Custom Texts
    -- Player
    E.db["unitframe"]["units"]["player"]["customTexts"] = E.db["unitframe"]["units"]["player"]["customTexts"] or {}
    E.db["unitframe"]["units"]["player"]["customTexts"]["!Health"] = {}
    E.db["unitframe"]["units"]["player"]["customTexts"]["!Name"] = {}
    E.db["unitframe"]["units"]["player"]["customTexts"]["!Power"] = {}
    -- Target
    E.db["unitframe"]["units"]["target"]["customTexts"] = E.db["unitframe"]["units"]["target"]["customTexts"] or {}
    E.db["unitframe"]["units"]["target"]["customTexts"]["!Health"] = {}
    E.db["unitframe"]["units"]["target"]["customTexts"]["!Name"] = {}
    E.db["unitframe"]["units"]["target"]["customTexts"]["!Power"] = {}
    E.db["unitframe"]["units"]["target"]["customTexts"]["!rare"] = {}
    -- Target of Target
    E.db["unitframe"]["units"]["targettarget"]["customTexts"] =
        E.db["unitframe"]["units"]["targettarget"]["customTexts"] or {}
    E.db["unitframe"]["units"]["targettarget"]["customTexts"]["!Name"] = {}
    -- Focus
    E.db["unitframe"]["units"]["focus"]["customTexts"] = E.db["unitframe"]["units"]["focus"]["customTexts"] or {}
    E.db["unitframe"]["units"]["focus"]["customTexts"]["!Health"] = {}
    E.db["unitframe"]["units"]["focus"]["customTexts"]["!Name"] = {}
    E.db["unitframe"]["units"]["focus"]["customTexts"]["!Power"] = {}
    -- Pet
    E.db["unitframe"]["units"]["pet"]["customTexts"] = E.db["unitframe"]["units"]["pet"]["customTexts"] or {}
    E.db["unitframe"]["units"]["pet"]["customTexts"]["!Health"] = {}
    E.db["unitframe"]["units"]["pet"]["customTexts"]["!Name"] = {}
    -- Party
    E.db["unitframe"]["units"]["party"]["customTexts"] = E.db["unitframe"]["units"]["party"]["customTexts"] or {}
    E.db["unitframe"]["units"]["party"]["customTexts"]["!Health"] = {}
    E.db["unitframe"]["units"]["party"]["customTexts"]["!Name"] = {}
    E.db["unitframe"]["units"]["party"]["customTexts"]["!HealthParty"] = nil
    E.db["unitframe"]["units"]["party"]["customTexts"]["!NameParty"] = nil
    -- Raid
    E.db["unitframe"]["units"]["raid"]["customTexts"] = E.db["unitframe"]["units"]["raid"]["customTexts"] or {}
    E.db["unitframe"]["units"]["raid"]["customTexts"]["!Name"] = {}
    -- Raid 40
    E.db["unitframe"]["units"]["raid40"]["customTexts"] = E.db["unitframe"]["units"]["raid40"]["customTexts"] or {}
    E.db["unitframe"]["units"]["raid40"]["customTexts"]["!Name"] = {}
    -- Boss
    E.db["unitframe"]["units"]["boss"]["customTexts"] = E.db["unitframe"]["units"]["boss"]["customTexts"] or {}
    E.db["unitframe"]["units"]["boss"]["customTexts"]["!Health"] = {}
    E.db["unitframe"]["units"]["boss"]["customTexts"]["!Name"] = {}
    E.db["unitframe"]["units"]["boss"]["customTexts"]["!Power"] = {}
    -- Arena
    E.db["unitframe"]["units"]["arena"]["customTexts"] = E.db["unitframe"]["units"]["arena"]["customTexts"] or {}
    E.db["unitframe"]["units"]["arena"]["customTexts"]["!Health"] = {}
    E.db["unitframe"]["units"]["arena"]["customTexts"]["!Name"] = {}
    E.db["unitframe"]["units"]["arena"]["customTexts"]["!Power"] = {}

    -- > UnitFrames
    -- Player
    E.db["unitframe"]["units"]["player"]["power"]["autoHide"] = false
    E.db["unitframe"]["units"]["player"]["customTexts"]["!Health"]["attachTextTo"] = "Health"
    E.db["unitframe"]["units"]["player"]["customTexts"]["!Health"]["enable"] = true
    E.db["unitframe"]["units"]["player"]["customTexts"]["!Health"]["font"] = "- Steelfish"
    E.db["unitframe"]["units"]["player"]["customTexts"]["!Health"]["fontOutline"] = "NONE"
    E.db["unitframe"]["units"]["player"]["customTexts"]["!Health"]["justifyH"] = "RIGHT"
    E.db["unitframe"]["units"]["player"]["customTexts"]["!Health"]["size"] = 22
    E.db["unitframe"]["units"]["player"]["customTexts"]["!Health"]["text_format"] =
        "[health:current:shortvalue] || [perhp]"
    E.db["unitframe"]["units"]["player"]["customTexts"]["!Health"]["xOffset"] = -10
    E.db["unitframe"]["units"]["player"]["customTexts"]["!Health"]["yOffset"] = 27
    E.db["unitframe"]["units"]["player"]["customTexts"]["!Name"]["attachTextTo"] = "Health"
    E.db["unitframe"]["units"]["player"]["customTexts"]["!Name"]["enable"] = true
    E.db["unitframe"]["units"]["player"]["customTexts"]["!Name"]["font"] = "- Big Noodle Titling"
    E.db["unitframe"]["units"]["player"]["customTexts"]["!Name"]["fontOutline"] = "NONE"
    E.db["unitframe"]["units"]["player"]["customTexts"]["!Name"]["justifyH"] = "LEFT"
    E.db["unitframe"]["units"]["player"]["customTexts"]["!Name"]["size"] = 26
    E.db["unitframe"]["units"]["player"]["customTexts"]["!Name"]["text_format"] = "[name:medium]"
    E.db["unitframe"]["units"]["player"]["customTexts"]["!Name"]["xOffset"] = 5
    E.db["unitframe"]["units"]["player"]["customTexts"]["!Name"]["yOffset"] = 27
    E.db["unitframe"]["units"]["player"]["customTexts"]["!Power"]["attachTextTo"] = "Power"
    E.db["unitframe"]["units"]["player"]["customTexts"]["!Power"]["enable"] = false
    E.db["unitframe"]["units"]["player"]["customTexts"]["!Power"]["font"] = "- BebasNeue RUS"
    E.db["unitframe"]["units"]["player"]["customTexts"]["!Power"]["fontOutline"] = "OUTLINE"
    E.db["unitframe"]["units"]["player"]["customTexts"]["!Power"]["justifyH"] = "CENTER"
    E.db["unitframe"]["units"]["player"]["customTexts"]["!Power"]["size"] = 22
    E.db["unitframe"]["units"]["player"]["customTexts"]["!Power"]["text_format"] = "[perpp]"
    E.db["unitframe"]["units"]["player"]["customTexts"]["!Power"]["xOffset"] = 0
    E.db["unitframe"]["units"]["player"]["customTexts"]["!Power"]["yOffset"] = 5
    E.db["unitframe"]["units"]["player"]["CombatIcon"]["anchorPoint"] = "LEFT"
    E.db["unitframe"]["units"]["player"]["CombatIcon"]["texture"] = "CUSTOM"
    E.db["unitframe"]["units"]["player"]["CombatIcon"]["size"] = 20
    E.db["unitframe"]["units"]["player"]["CombatIcon"]["customTexture"] = I.General.MediaPath .. "Textures\\Combat.blp"
    E.db["unitframe"]["units"]["player"]["RestIcon"]["enable"] = true
    E.db["unitframe"]["units"]["player"]["RestIcon"]["anchorPoint"] = "TOPLEFT"
    E.db["unitframe"]["units"]["player"]["RestIcon"]["defaultColor"] = false
    E.db["unitframe"]["units"]["player"]["RestIcon"]["size"] = 36
    E.db["unitframe"]["units"]["player"]["RestIcon"]["texture"] = "CUSTOM"
    E.db["unitframe"]["units"]["player"]["RestIcon"]["xOffset"] = 25
    E.db["unitframe"]["units"]["player"]["RestIcon"]["customTexture"] = I.General.MediaPath .. "Textures\\Resting.tga"
    E.db["unitframe"]["units"]["player"]["aurabar"]["enable"] = false
    E.db["unitframe"]["units"]["player"]["aurabar"]["height"] = 26
    E.db["unitframe"]["units"]["player"]["buffs"]["attachTo"] = "FRAME"
    E.db["unitframe"]["units"]["player"]["buffs"]["perrow"] = 7
    E.db["unitframe"]["units"]["player"]["castbar"]["customColor"]["useClassColor"] = true
    E.db["unitframe"]["units"]["player"]["castbar"]["customTextFont"]["enable"] = true
    E.db["unitframe"]["units"]["player"]["castbar"]["customTextFont"]["font"] = "- Big Noodle Titling"
    E.db["unitframe"]["units"]["player"]["castbar"]["customTextFont"]["fontSize"] = 20
    E.db["unitframe"]["units"]["player"]["castbar"]["customTextFont"]["fontStyle"] = "NONE"
    E.db["unitframe"]["units"]["player"]["castbar"]["customTimeFont"]["enable"] = true
    E.db["unitframe"]["units"]["player"]["castbar"]["customTimeFont"]["font"] = "- Big Noodle Titling"
    E.db["unitframe"]["units"]["player"]["castbar"]["customTimeFont"]["fontSize"] = 20
    E.db["unitframe"]["units"]["player"]["castbar"]["customTimeFont"]["fontStyle"] = "NONE"
    E.db["unitframe"]["units"]["player"]["castbar"]["height"] = 25
    E.db["unitframe"]["units"]["player"]["castbar"]["icon"] = false
    E.db["unitframe"]["units"]["player"]["castbar"]["iconAttachedTo"] = "Castbar"
    E.db["unitframe"]["units"]["player"]["castbar"]["insideInfoPanel"] = false
    E.db["unitframe"]["units"]["player"]["castbar"]["textColor"]["b"] = 1
    E.db["unitframe"]["units"]["player"]["castbar"]["textColor"]["g"] = 1
    E.db["unitframe"]["units"]["player"]["castbar"]["textColor"]["r"] = 1
    E.db["unitframe"]["units"]["player"]["castbar"]["xOffsetText"] = 5
    E.db["unitframe"]["units"]["player"]["castbar"]["xOffsetTime"] = -10
    E.db["unitframe"]["units"]["player"]["classbar"]["detachFromFrame"] = true
    E.db["unitframe"]["units"]["player"]["classbar"]["detachedWidth"] = 120
    E.db["unitframe"]["units"]["player"]["classbar"]["enable"] = false
    E.db["unitframe"]["units"]["player"]["classbar"]["spacing"] = 1
    E.db["unitframe"]["units"]["player"]["debuffs"]["countFont"] = "- Big Noodle Titling"
    E.db["unitframe"]["units"]["player"]["debuffs"]["countFontSize"] = 16
    E.db["unitframe"]["units"]["player"]["debuffs"]["durationPosition"] = "TOP"
    E.db["unitframe"]["units"]["player"]["debuffs"]["sizeOverride"] = 30
    E.db["unitframe"]["units"]["player"]["debuffs"]["yOffset"] = 25
    E.db["unitframe"]["units"]["player"]["disableMouseoverGlow"] = true
    E.db["unitframe"]["units"]["player"]["fader"]["enable"] = true
    E.db["unitframe"]["units"]["player"]["fader"]["minAlpha"] = 0
    E.db["unitframe"]["units"]["player"]["fader"]["power"] = false
    E.db["unitframe"]["units"]["player"]["fader"]["vehicle"] = false
    E.db["unitframe"]["units"]["player"]["healPrediction"]["absorbStyle"] = "REVERSED"
    E.db["unitframe"]["units"]["player"]["health"]["attachTextTo"] = "InfoPanel"
    E.db["unitframe"]["units"]["player"]["health"]["text_format"] = ""
    E.db["unitframe"]["units"]["player"]["portrait"]["fullOverlay"] = true
    E.db["unitframe"]["units"]["player"]["portrait"]["overlay"] = true
    E.db["unitframe"]["units"]["player"]["portrait"]["overlayAlpha"] = 0.25
    E.db["unitframe"]["units"]["player"]["portrait"]["xOffset"] = -0.06
    E.db["unitframe"]["units"]["player"]["power"]["attachTextTo"] = "Power"
    E.db["unitframe"]["units"]["player"]["power"]["detachFromFrame"] = true
    E.db["unitframe"]["units"]["player"]["power"]["detachedWidth"] = 120
    E.db["unitframe"]["units"]["player"]["power"]["text_format"] = ""
    E.db["unitframe"]["units"]["player"]["power"]["enable"] = false
    E.db["unitframe"]["units"]["player"]["raidicon"]["attachTo"] = "CENTER"
    E.db["unitframe"]["units"]["player"]["raidicon"]["size"] = 24
    E.db["unitframe"]["units"]["player"]["raidicon"]["yOffset"] = 0
    E.db["unitframe"]["units"]["player"]["width"] = 250
    -- Arena
    E.db["unitframe"]["units"]["arena"]["buffs"]["countFont"] = "- Steelfish"
    E.db["unitframe"]["units"]["arena"]["buffs"]["countFontSize"] = 20
    E.db["unitframe"]["units"]["arena"]["buffs"]["priority"] =
        "Blacklist,CastByUnit,Dispellable,Whitelist,RaidBuffsElvUI"
    E.db["unitframe"]["units"]["arena"]["buffs"]["sizeOverride"] = 24
    E.db["unitframe"]["units"]["arena"]["castbar"]["width"] = 250
    E.db["unitframe"]["units"]["arena"]["customTexts"]["!Health"]["attachTextTo"] = "Health"
    E.db["unitframe"]["units"]["arena"]["customTexts"]["!Health"]["enable"] = true
    E.db["unitframe"]["units"]["arena"]["customTexts"]["!Health"]["font"] = "- Steelfish"
    E.db["unitframe"]["units"]["arena"]["customTexts"]["!Health"]["fontOutline"] = "NONE"
    E.db["unitframe"]["units"]["arena"]["customTexts"]["!Health"]["justifyH"] = "LEFT"
    E.db["unitframe"]["units"]["arena"]["customTexts"]["!Health"]["size"] = 20
    E.db["unitframe"]["units"]["arena"]["customTexts"]["!Health"]["text_format"] =
        "[perhp] || [health:current:shortvalue]"
    E.db["unitframe"]["units"]["arena"]["customTexts"]["!Health"]["xOffset"] = 5
    E.db["unitframe"]["units"]["arena"]["customTexts"]["!Name"]["attachTextTo"] = "Health"
    E.db["unitframe"]["units"]["arena"]["customTexts"]["!Name"]["enable"] = true
    E.db["unitframe"]["units"]["arena"]["customTexts"]["!Name"]["font"] = "- Big Noodle Titling"
    E.db["unitframe"]["units"]["arena"]["customTexts"]["!Name"]["fontOutline"] = "NONE"
    E.db["unitframe"]["units"]["arena"]["customTexts"]["!Name"]["justifyH"] = "RIGHT"
    E.db["unitframe"]["units"]["arena"]["customTexts"]["!Name"]["size"] = 24
    E.db["unitframe"]["units"]["arena"]["customTexts"]["!Name"]["text_format"] = "[name:medium]"
    E.db["unitframe"]["units"]["arena"]["customTexts"]["!Name"]["xOffset"] = -5
    E.db["unitframe"]["units"]["arena"]["customTexts"]["!Power"]["attachTextTo"] = "Power"
    E.db["unitframe"]["units"]["arena"]["customTexts"]["!Power"]["enable"] = true
    E.db["unitframe"]["units"]["arena"]["customTexts"]["!Power"]["font"] = "- Steelfish"
    E.db["unitframe"]["units"]["arena"]["customTexts"]["!Power"]["fontOutline"] = "OUTLINE"
    E.db["unitframe"]["units"]["arena"]["customTexts"]["!Power"]["justifyH"] = "LEFT"
    E.db["unitframe"]["units"]["arena"]["customTexts"]["!Power"]["size"] = 20
    E.db["unitframe"]["units"]["arena"]["customTexts"]["!Power"]["text_format"] = "[perpp]"
    E.db["unitframe"]["units"]["arena"]["customTexts"]["!Power"]["xOffset"] = 10
    E.db["unitframe"]["units"]["arena"]["customTexts"]["!Power"]["yOffset"] = 0
    E.db["unitframe"]["units"]["arena"]["debuffs"]["countFont"] = "- Steelfish"
    E.db["unitframe"]["units"]["arena"]["debuffs"]["countFontSize"] = 20
    E.db["unitframe"]["units"]["arena"]["debuffs"]["desaturate"] = true
    E.db["unitframe"]["units"]["arena"]["debuffs"]["priority"] =
        "Blacklist,Boss,Personal,RaidDebuffs,CastByUnit,Whitelist"
    E.db["unitframe"]["units"]["arena"]["debuffs"]["sizeOverride"] = 25
    E.db["unitframe"]["units"]["arena"]["health"]["text_format"] = ""
    E.db["unitframe"]["units"]["arena"]["height"] = 40
    E.db["unitframe"]["units"]["arena"]["name"]["text_format"] = ""
    E.db["unitframe"]["units"]["arena"]["power"]["height"] = 10
    E.db["unitframe"]["units"]["arena"]["power"]["text_format"] = ""
    E.db["unitframe"]["units"]["arena"]["pvpTrinket"]["size"] = 30
    E.db["unitframe"]["units"]["arena"]["spacing"] = 40
    E.db["unitframe"]["units"]["arena"]["width"] = 250
    -- Boss
    E.db["unitframe"]["units"]["boss"]["buffs"]["countFont"] = "- Steelfish"
    E.db["unitframe"]["units"]["boss"]["buffs"]["countFontSize"] = 20
    E.db["unitframe"]["units"]["boss"]["buffs"]["maxDuration"] = 300
    E.db["unitframe"]["units"]["boss"]["buffs"]["sizeOverride"] = 25
    E.db["unitframe"]["units"]["boss"]["buffs"]["yOffset"] = 16
    E.db["unitframe"]["units"]["boss"]["castbar"]["width"] = 200
    E.db["unitframe"]["units"]["boss"]["customTexts"]["!Health"]["attachTextTo"] = "Health"
    E.db["unitframe"]["units"]["boss"]["customTexts"]["!Health"]["enable"] = true
    E.db["unitframe"]["units"]["boss"]["customTexts"]["!Health"]["font"] = "- Steelfish"
    E.db["unitframe"]["units"]["boss"]["customTexts"]["!Health"]["fontOutline"] = "NONE"
    E.db["unitframe"]["units"]["boss"]["customTexts"]["!Health"]["justifyH"] = "LEFT"
    E.db["unitframe"]["units"]["boss"]["customTexts"]["!Health"]["size"] = 24
    E.db["unitframe"]["units"]["boss"]["customTexts"]["!Health"]["text_format"] = "[perhp]"
    E.db["unitframe"]["units"]["boss"]["customTexts"]["!Health"]["xOffset"] = 5
    E.db["unitframe"]["units"]["boss"]["customTexts"]["!Name"]["attachTextTo"] = "Health"
    E.db["unitframe"]["units"]["boss"]["customTexts"]["!Name"]["enable"] = true
    E.db["unitframe"]["units"]["boss"]["customTexts"]["!Name"]["font"] = "- Big Noodle Titling"
    E.db["unitframe"]["units"]["boss"]["customTexts"]["!Name"]["fontOutline"] = "NONE"
    E.db["unitframe"]["units"]["boss"]["customTexts"]["!Name"]["justifyH"] = "RIGHT"
    E.db["unitframe"]["units"]["boss"]["customTexts"]["!Name"]["size"] = 24
    E.db["unitframe"]["units"]["boss"]["customTexts"]["!Name"]["text_format"] = "[name:abbrev:medium]"
    E.db["unitframe"]["units"]["boss"]["customTexts"]["!Name"]["xOffset"] = -5
    E.db["unitframe"]["units"]["boss"]["customTexts"]["!Power"]["attachTextTo"] = "Power"
    E.db["unitframe"]["units"]["boss"]["customTexts"]["!Power"]["enable"] = true
    E.db["unitframe"]["units"]["boss"]["customTexts"]["!Power"]["font"] = "- Steelfish"
    E.db["unitframe"]["units"]["boss"]["customTexts"]["!Power"]["fontOutline"] = "OUTLINE"
    E.db["unitframe"]["units"]["boss"]["customTexts"]["!Power"]["justifyH"] = "LEFT"
    E.db["unitframe"]["units"]["boss"]["customTexts"]["!Power"]["size"] = 20
    E.db["unitframe"]["units"]["boss"]["customTexts"]["!Power"]["text_format"] = "[perpp]"
    E.db["unitframe"]["units"]["boss"]["customTexts"]["!Power"]["xOffset"] = 70
    E.db["unitframe"]["units"]["boss"]["customTexts"]["!Power"]["yOffset"] = 0
    E.db["unitframe"]["units"]["boss"]["debuffs"]["countFont"] = "- Steelfish"
    E.db["unitframe"]["units"]["boss"]["debuffs"]["countFontSize"] = 20
    E.db["unitframe"]["units"]["boss"]["debuffs"]["maxDuration"] = 300
    E.db["unitframe"]["units"]["boss"]["debuffs"]["sizeOverride"] = 25
    E.db["unitframe"]["units"]["boss"]["debuffs"]["yOffset"] = -16
    E.db["unitframe"]["units"]["boss"]["health"]["text_format"] = ""
    E.db["unitframe"]["units"]["boss"]["height"] = 30
    E.db["unitframe"]["units"]["boss"]["infoPanel"]["height"] = 17
    E.db["unitframe"]["units"]["boss"]["name"]["text_format"] = ""
    E.db["unitframe"]["units"]["boss"]["power"]["text_format"] = ""
    E.db["unitframe"]["units"]["boss"]["power"]["width"] = "spaced"
    E.db["unitframe"]["units"]["boss"]["spacing"] = 45
    E.db["unitframe"]["units"]["boss"]["width"] = 200
    -- Focus
    E.db["unitframe"]["units"]["focus"]["CombatIcon"]["anchorPoint"] = "LEFT"
    E.db["unitframe"]["units"]["focus"]["CombatIcon"]["texture"] = "CUSTOM"
    E.db["unitframe"]["units"]["focus"]["CombatIcon"]["size"] = 20
    E.db["unitframe"]["units"]["focus"]["CombatIcon"]["customTexture"] = I.General.MediaPath .. "Textures\\Combat.blp"
    E.db["unitframe"]["units"]["focus"]["aurabar"]["detachedWidth"] = 270
    E.db["unitframe"]["units"]["focus"]["aurabar"]["height"] = 26
    E.db["unitframe"]["units"]["focus"]["aurabar"]["maxBars"] = 6
    E.db["unitframe"]["units"]["focus"]["buffs"]["anchorPoint"] = "TOPLEFT"
    E.db["unitframe"]["units"]["focus"]["buffs"]["countFont"] = "- Steelfish"
    E.db["unitframe"]["units"]["focus"]["buffs"]["countFontSize"] = 20
    E.db["unitframe"]["units"]["focus"]["buffs"]["enable"] = true
    E.db["unitframe"]["units"]["focus"]["buffs"]["maxDuration"] = 0
    E.db["unitframe"]["units"]["focus"]["buffs"]["perrow"] = 5
    E.db["unitframe"]["units"]["focus"]["buffs"]["priority"] =
        "Blacklist,Personal,PlayerBuffs,Whitelist,blockNoDuration,nonPersonal"
    E.db["unitframe"]["units"]["focus"]["buffs"]["sizeOverride"] = 24
    E.db["unitframe"]["units"]["focus"]["buffs"]["spacing"] = 0
    E.db["unitframe"]["units"]["focus"]["buffs"]["xOffset"] = 3
    E.db["unitframe"]["units"]["focus"]["buffs"]["yOffset"] = 25
    E.db["unitframe"]["units"]["focus"]["castbar"]["customColor"]["useClassColor"] = true
    E.db["unitframe"]["units"]["focus"]["castbar"]["customTextFont"]["enable"] = true
    E.db["unitframe"]["units"]["focus"]["castbar"]["customTextFont"]["font"] = "- Big Noodle Titling"
    E.db["unitframe"]["units"]["focus"]["castbar"]["customTextFont"]["fontSize"] = 20
    E.db["unitframe"]["units"]["focus"]["castbar"]["customTextFont"]["fontStyle"] = "NONE"
    E.db["unitframe"]["units"]["focus"]["castbar"]["customTimeFont"]["enable"] = true
    E.db["unitframe"]["units"]["focus"]["castbar"]["customTimeFont"]["font"] = "- Big Noodle Titling"
    E.db["unitframe"]["units"]["focus"]["castbar"]["customTimeFont"]["fontSize"] = 20
    E.db["unitframe"]["units"]["focus"]["castbar"]["customTimeFont"]["fontStyle"] = "NONE"
    E.db["unitframe"]["units"]["focus"]["castbar"]["height"] = 20
    E.db["unitframe"]["units"]["focus"]["castbar"]["icon"] = false
    E.db["unitframe"]["units"]["focus"]["castbar"]["iconAttachedTo"] = "Castbar"
    E.db["unitframe"]["units"]["focus"]["castbar"]["insideInfoPanel"] = false
    E.db["unitframe"]["units"]["focus"]["castbar"]["textColor"]["b"] = 1
    E.db["unitframe"]["units"]["focus"]["castbar"]["textColor"]["g"] = 1
    E.db["unitframe"]["units"]["focus"]["castbar"]["textColor"]["r"] = 1
    E.db["unitframe"]["units"]["focus"]["castbar"]["width"] = 250
    E.db["unitframe"]["units"]["focus"]["castbar"]["xOffsetText"] = 5
    E.db["unitframe"]["units"]["focus"]["castbar"]["xOffsetTime"] = -10
    E.db["unitframe"]["units"]["focus"]["customTexts"]["!Health"]["attachTextTo"] = "Health"
    E.db["unitframe"]["units"]["focus"]["customTexts"]["!Health"]["enable"] = true
    E.db["unitframe"]["units"]["focus"]["customTexts"]["!Health"]["font"] = "- Steelfish"
    E.db["unitframe"]["units"]["focus"]["customTexts"]["!Health"]["fontOutline"] = "NONE"
    E.db["unitframe"]["units"]["focus"]["customTexts"]["!Health"]["justifyH"] = "RIGHT"
    E.db["unitframe"]["units"]["focus"]["customTexts"]["!Health"]["size"] = 22
    E.db["unitframe"]["units"]["focus"]["customTexts"]["!Health"]["text_format"] =
        "[health:current:shortvalue] || [perhp]"
    E.db["unitframe"]["units"]["focus"]["customTexts"]["!Health"]["xOffset"] = -10
    E.db["unitframe"]["units"]["focus"]["customTexts"]["!Name"]["attachTextTo"] = "Health"
    E.db["unitframe"]["units"]["focus"]["customTexts"]["!Name"]["enable"] = true
    E.db["unitframe"]["units"]["focus"]["customTexts"]["!Name"]["font"] = "- Big Noodle Titling"
    E.db["unitframe"]["units"]["focus"]["customTexts"]["!Name"]["fontOutline"] = "NONE"
    E.db["unitframe"]["units"]["focus"]["customTexts"]["!Name"]["justifyH"] = "LEFT"
    E.db["unitframe"]["units"]["focus"]["customTexts"]["!Name"]["size"] = 26
    E.db["unitframe"]["units"]["focus"]["customTexts"]["!Name"]["text_format"] = "[name:medium]"
    E.db["unitframe"]["units"]["focus"]["customTexts"]["!Name"]["xOffset"] = 5
    E.db["unitframe"]["units"]["focus"]["customTexts"]["!Power"]["attachTextTo"] = "Power"
    E.db["unitframe"]["units"]["focus"]["customTexts"]["!Power"]["enable"] = false
    E.db["unitframe"]["units"]["focus"]["customTexts"]["!Power"]["font"] = "- BebasNeue RUS"
    E.db["unitframe"]["units"]["focus"]["customTexts"]["!Power"]["fontOutline"] = "OUTLINE"
    E.db["unitframe"]["units"]["focus"]["customTexts"]["!Power"]["justifyH"] = "CENTER"
    E.db["unitframe"]["units"]["focus"]["customTexts"]["!Power"]["size"] = 22
    E.db["unitframe"]["units"]["focus"]["customTexts"]["!Power"]["text_format"] = "[perpp]"
    E.db["unitframe"]["units"]["focus"]["customTexts"]["!Power"]["xOffset"] = 0
    E.db["unitframe"]["units"]["focus"]["customTexts"]["!Power"]["yOffset"] = 5
    E.db["unitframe"]["units"]["focus"]["debuffs"]["countFont"] = "- Steelfish"
    E.db["unitframe"]["units"]["focus"]["debuffs"]["countFontSize"] = 20
    E.db["unitframe"]["units"]["focus"]["debuffs"]["durationPosition"] = "TOP"
    E.db["unitframe"]["units"]["focus"]["debuffs"]["maxDuration"] = 0
    E.db["unitframe"]["units"]["focus"]["debuffs"]["priority"] = "Blacklist,Personal,nonPersonal"
    E.db["unitframe"]["units"]["focus"]["debuffs"]["sizeOverride"] = 24
    E.db["unitframe"]["units"]["focus"]["debuffs"]["spacing"] = 0
    E.db["unitframe"]["units"]["focus"]["debuffs"]["xOffset"] = -3
    E.db["unitframe"]["units"]["focus"]["debuffs"]["yOffset"] = 25
    E.db["unitframe"]["units"]["focus"]["disableMouseoverGlow"] = true
    E.db["unitframe"]["units"]["focus"]["disableTargetGlow"] = true
    E.db["unitframe"]["units"]["focus"]["health"]["attachTextTo"] = "InfoPanel"
    E.db["unitframe"]["units"]["focus"]["health"]["position"] = "LEFT"
    E.db["unitframe"]["units"]["focus"]["health"]["xOffset"] = 2
    E.db["unitframe"]["units"]["focus"]["height"] = 30
    E.db["unitframe"]["units"]["focus"]["infoPanel"]["height"] = 20
    E.db["unitframe"]["units"]["focus"]["name"]["text_format"] = ""
    E.db["unitframe"]["units"]["focus"]["orientation"] = "LEFT"
    E.db["unitframe"]["units"]["focus"]["portrait"]["fullOverlay"] = true
    E.db["unitframe"]["units"]["focus"]["portrait"]["overlay"] = true
    E.db["unitframe"]["units"]["focus"]["portrait"]["overlayAlpha"] = 0.25
    E.db["unitframe"]["units"]["focus"]["portrait"]["xOffset"] = -0.06
    E.db["unitframe"]["units"]["focus"]["power"]["attachTextTo"] = "Power"
    E.db["unitframe"]["units"]["focus"]["power"]["detachFromFrame"] = true
    E.db["unitframe"]["units"]["focus"]["power"]["detachedWidth"] = 120
    E.db["unitframe"]["units"]["focus"]["power"]["position"] = "RIGHT"
    E.db["unitframe"]["units"]["focus"]["power"]["xOffset"] = -2
    E.db["unitframe"]["units"]["focus"]["raidicon"]["attachTo"] = "CENTER"
    E.db["unitframe"]["units"]["focus"]["raidicon"]["size"] = 24
    E.db["unitframe"]["units"]["focus"]["raidicon"]["yOffset"] = 0
    E.db["unitframe"]["units"]["focus"]["width"] = 250
    -- Party
    -- Custom Texts
    E.db["unitframe"]["units"]["party"]["customTexts"]["!Health"]["attachTextTo"] = "Health"
    E.db["unitframe"]["units"]["party"]["customTexts"]["!Health"]["enable"] = true
    E.db["unitframe"]["units"]["party"]["customTexts"]["!Health"]["font"] = "- Steelfish"
    E.db["unitframe"]["units"]["party"]["customTexts"]["!Health"]["fontOutline"] = "NONE"
    E.db["unitframe"]["units"]["party"]["customTexts"]["!Health"]["justifyH"] = "RIGHT"
    E.db["unitframe"]["units"]["party"]["customTexts"]["!Health"]["text_format"] = "[perhp]"
    E.db["unitframe"]["units"]["party"]["customTexts"]["!Health"]["xOffset"] = -10
    E.db["unitframe"]["units"]["party"]["customTexts"]["!Name"]["attachTextTo"] = "Health"
    E.db["unitframe"]["units"]["party"]["customTexts"]["!Name"]["enable"] = true
    E.db["unitframe"]["units"]["party"]["customTexts"]["!Name"]["font"] = "- Big Noodle Titling"
    E.db["unitframe"]["units"]["party"]["customTexts"]["!Name"]["fontOutline"] = "NONE"
    E.db["unitframe"]["units"]["party"]["customTexts"]["!Name"]["justifyH"] = "LEFT"
    E.db["unitframe"]["units"]["party"]["customTexts"]["!Name"]["size"] = 26
    -- Buffs
    E.db["unitframe"]["units"]["party"]["buffIndicator"]["size"] = 10
    E.db["unitframe"]["units"]["party"]["buffs"]["anchorPoint"] = "BOTTOMLEFT"
    E.db["unitframe"]["units"]["party"]["buffs"]["countFont"] = "- Steelfish"
    E.db["unitframe"]["units"]["party"]["buffs"]["countFontSize"] = 16
    E.db["unitframe"]["units"]["party"]["buffs"]["perrow"] = 5
    E.db["unitframe"]["units"]["party"]["buffs"]["sizeOverride"] = 29
    E.db["unitframe"]["units"]["party"]["buffs"]["spacing"] = 1
    -- Debuffs
    E.db["unitframe"]["units"]["party"]["debuffs"]["attachTo"] = "HEALTH"
    E.db["unitframe"]["units"]["party"]["debuffs"]["countFont"] = "- Steelfish"
    E.db["unitframe"]["units"]["party"]["debuffs"]["countFontSize"] = 16
    E.db["unitframe"]["units"]["party"]["debuffs"]["perrow"] = 5
    E.db["unitframe"]["units"]["party"]["debuffs"]["priority"] =
        "Blacklist,Dispellable,Boss,RaidDebuffs,CCDebuffs,Whitelist"
    E.db["unitframe"]["units"]["party"]["debuffs"]["sizeOverride"] = 29
    E.db["unitframe"]["units"]["party"]["debuffs"]["spacing"] = 1
    -- Other
    E.db["unitframe"]["units"]["party"]["groupBy"] = "ROLE"
    E.db["unitframe"]["units"]["party"]["healPrediction"]["absorbStyle"] = "REVERSED"
    E.db["unitframe"]["units"]["party"]["healPrediction"]["enable"] = true
    E.db["unitframe"]["units"]["party"]["health"]["position"] = "CENTER"
    E.db["unitframe"]["units"]["party"]["health"]["text_format"] = ""
    E.db["unitframe"]["units"]["party"]["health"]["xOffset"] = 72
    E.db["unitframe"]["units"]["party"]["horizontalSpacing"] = 3
    E.db["unitframe"]["units"]["party"]["name"]["text_format"] = ""
    E.db["unitframe"]["units"]["party"]["petsGroup"]["anchorPoint"] = "BOTTOM"
    E.db["unitframe"]["units"]["party"]["phaseIndicator"]["scale"] = 1
    E.db["unitframe"]["units"]["party"]["portrait"]["camDistanceScale"] = 3
    E.db["unitframe"]["units"]["party"]["portrait"]["fullOverlay"] = true
    E.db["unitframe"]["units"]["party"]["portrait"]["overlay"] = true
    E.db["unitframe"]["units"]["party"]["portrait"]["overlayAlpha"] = 0.3
    E.db["unitframe"]["units"]["party"]["portrait"]["width"] = 62
    E.db["unitframe"]["units"]["party"]["power"]["attachTextTo"] = "Frame"
    E.db["unitframe"]["units"]["party"]["power"]["position"] = "BOTTOMLEFT"
    E.db["unitframe"]["units"]["party"]["power"]["text_format"] = " "
    E.db["unitframe"]["units"]["party"]["power"]["xOffset"] = 0
    E.db["unitframe"]["units"]["party"]["raidRoleIcons"]["position"] = "TOPRIGHT"
    E.db["unitframe"]["units"]["party"]["raidWideSorting"] = true
    E.db["unitframe"]["units"]["party"]["raidicon"]["size"] = 26
    E.db["unitframe"]["units"]["party"]["raidicon"]["xOffset"] = -50
    E.db["unitframe"]["units"]["party"]["raidicon"]["yOffset"] = -10
    E.db["unitframe"]["units"]["party"]["rdebuffs"]["font"] = "- Steelfish"
    E.db["unitframe"]["units"]["party"]["rdebuffs"]["fontOutline"] = "OUTLINE"
    E.db["unitframe"]["units"]["party"]["rdebuffs"]["fontSize"] = 16
    E.db["unitframe"]["units"]["party"]["rdebuffs"]["size"] = 30
    E.db["unitframe"]["units"]["party"]["rdebuffs"]["yOffset"] = 20
    E.db["unitframe"]["units"]["party"]["readycheckIcon"]["position"] = "CENTER"
    E.db["unitframe"]["units"]["party"]["readycheckIcon"]["size"] = 40
    E.db["unitframe"]["units"]["party"]["readycheckIcon"]["yOffset"] = 0
    E.db["unitframe"]["units"]["party"]["startFromCenter"] = true
    E.db["unitframe"]["units"]["party"]["targetsGroup"]["anchorPoint"] = "BOTTOM"
    E.db["unitframe"]["units"]["party"]["targetsGroup"]["name"]["text_format"] = "||cffFFFFFF[name:veryshort]||r"
    E.db["unitframe"]["units"]["party"]["targetsGroup"]["width"] = 43
    E.db["unitframe"]["units"]["party"]["targetsGroup"]["xOffset"] = -93
    E.db["unitframe"]["units"]["party"]["targetsGroup"]["yOffset"] = 28
    -- Pet
    E.db["unitframe"]["units"]["pet"]["castbar"]["height"] = 12
    E.db["unitframe"]["units"]["pet"]["castbar"]["iconSize"] = 32
    E.db["unitframe"]["units"]["pet"]["castbar"]["width"] = 100
    E.db["unitframe"]["units"]["pet"]["customTexts"]["!Health"]["attachTextTo"] = "Health"
    E.db["unitframe"]["units"]["pet"]["customTexts"]["!Health"]["enable"] = false
    E.db["unitframe"]["units"]["pet"]["customTexts"]["!Health"]["font"] = "- Steelfish"
    E.db["unitframe"]["units"]["pet"]["customTexts"]["!Health"]["fontOutline"] = "NONE"
    E.db["unitframe"]["units"]["pet"]["customTexts"]["!Health"]["justifyH"] = "RIGHT"
    E.db["unitframe"]["units"]["pet"]["customTexts"]["!Health"]["size"] = 14
    E.db["unitframe"]["units"]["pet"]["customTexts"]["!Health"]["text_format"] = "[perhp]"
    E.db["unitframe"]["units"]["pet"]["customTexts"]["!Health"]["xOffset"] = -1
    E.db["unitframe"]["units"]["pet"]["customTexts"]["!Name"]["attachTextTo"] = "Health"
    E.db["unitframe"]["units"]["pet"]["customTexts"]["!Name"]["enable"] = true
    E.db["unitframe"]["units"]["pet"]["customTexts"]["!Name"]["font"] = "- Big Noodle Titling"
    E.db["unitframe"]["units"]["pet"]["customTexts"]["!Name"]["fontOutline"] = "NONE"
    E.db["unitframe"]["units"]["pet"]["customTexts"]["!Name"]["justifyH"] = "CENTER"
    E.db["unitframe"]["units"]["pet"]["customTexts"]["!Name"]["size"] = 16
    E.db["unitframe"]["units"]["pet"]["customTexts"]["!Name"]["text_format"] = "[name:short]"
    E.db["unitframe"]["units"]["pet"]["customTexts"]["!Name"]["xOffset"] = 5
    E.db["unitframe"]["units"]["pet"]["debuffs"]["anchorPoint"] = "TOPRIGHT"
    E.db["unitframe"]["units"]["pet"]["debuffs"]["enable"] = true
    E.db["unitframe"]["units"]["pet"]["disableTargetGlow"] = false
    E.db["unitframe"]["units"]["pet"]["fader"]["combat"] = true
    E.db["unitframe"]["units"]["pet"]["fader"]["health"] = true
    E.db["unitframe"]["units"]["pet"]["fader"]["hover"] = true
    E.db["unitframe"]["units"]["pet"]["fader"]["minAlpha"] = 0
    E.db["unitframe"]["units"]["pet"]["fader"]["playertarget"] = true
    E.db["unitframe"]["units"]["pet"]["fader"]["range"] = false
    E.db["unitframe"]["units"]["pet"]["fader"]["unittarget"] = true
    E.db["unitframe"]["units"]["pet"]["infoPanel"]["height"] = 14
    E.db["unitframe"]["units"]["pet"]["name"]["text_format"] = ""
    E.db["unitframe"]["units"]["pet"]["power"]["enable"] = false
    E.db["unitframe"]["units"]["pet"]["width"] = 100
    -- Raid
    E.db["unitframe"]["units"]["raid"]["customTexts"]["!Name"]["attachTextTo"] = "Frame"
    E.db["unitframe"]["units"]["raid"]["customTexts"]["!Name"]["enable"] = true
    E.db["unitframe"]["units"]["raid"]["customTexts"]["!Name"]["font"] = "- Big Noodle Titling"
    E.db["unitframe"]["units"]["raid"]["customTexts"]["!Name"]["fontOutline"] = "NONE"
    E.db["unitframe"]["units"]["raid"]["customTexts"]["!Name"]["justifyH"] = "CENTER"
    E.db["unitframe"]["units"]["raid"]["customTexts"]["!Name"]["text_format"] = "[name:short]"
    E.db["unitframe"]["units"]["raid"]["customTexts"]["!Name"]["size"] = 16
    E.db["unitframe"]["units"]["raid"]["customTexts"]["!Name"]["xOffset"] = 0
    E.db["unitframe"]["units"]["raid"]["customTexts"]["!Name"]["yOffset"] = 0
    E.db["unitframe"]["units"]["raid"]["customTexts"]["!Name"]["fontOutline"] = "OUTLINE"
    E.db["unitframe"]["units"]["raid"]["rdebuffs"]["size"] = 20
    E.db["unitframe"]["units"]["raid"]["width"] = 80
    E.db["unitframe"]["units"]["raid"]["height"] = 35
    E.db["unitframe"]["units"]["raid"]["verticalSpacing"] = 1
    E.db["unitframe"]["units"]["raid"]["horizontalSpacing"] = 1
    E.db["unitframe"]["units"]["raid"]["groupSpacing"] = 0
    E.db["unitframe"]["units"]["raid"]["groupBy"] = "ROLE"
    E.db["unitframe"]["units"]["raid"]["groupsPerRowCol"] = 1
    E.db["unitframe"]["units"]["raid"]["healPrediction"]["absorbStyle"] = "REVERSED"
    E.db["unitframe"]["units"]["raid"]["healPrediction"]["enable"] = true
    E.db["unitframe"]["units"]["raid"]["health"]["text_format"] = ""
    E.db["unitframe"]["units"]["raid"]["name"]["text_format"] = ""
    E.db["unitframe"]["units"]["raid"]["numGroups"] = 5
    E.db["unitframe"]["units"]["raid"]["power"]["enable"] = false
    E.db["unitframe"]["units"]["raid"]["raidWideSorting"] = false
    E.db["unitframe"]["units"]["raid"]["startFromCenter"] = false
    E.db["unitframe"]["units"]["raid"]["rdebuffs"]["duration"]["color"]["b"] = 0.91764705882353
    E.db["unitframe"]["units"]["raid"]["rdebuffs"]["duration"]["color"]["g"] = 0.94117647058824
    E.db["unitframe"]["units"]["raid"]["rdebuffs"]["font"] = "- Big Noodle Titling"
    E.db["unitframe"]["units"]["raid"]["rdebuffs"]["fontOutline"] = "OUTLINE"
    E.db["unitframe"]["units"]["raid"]["rdebuffs"]["fontSize"] = 14
    E.db["unitframe"]["units"]["raid"]["rdebuffs"]["stack"]["color"]["g"] = 0.91372549019608
    E.db["unitframe"]["units"]["raid"]["rdebuffs"]["stack"]["position"] = "BOTTOMRIGHT"
    E.db["unitframe"]["units"]["raid"]["rdebuffs"]["stack"]["yOffset"] = 0
    E.db["unitframe"]["units"]["raid"]["rdebuffs"]["yOffset"] = 5
    E.db["unitframe"]["units"]["raid"]["readycheckIcon"]["size"] = 24
    E.db["unitframe"]["units"]["raid"]["roleIcon"]["damager"] = false
    E.db["unitframe"]["units"]["raid"]["roleIcon"]["position"] = "TOPLEFT"
    E.db["unitframe"]["units"]["raid"]["roleIcon"]["size"] = 16
    E.db["unitframe"]["units"]["raid"]["roleIcon"]["xOffset"] = -10
    E.db["unitframe"]["units"]["raid"]["roleIcon"]["yOffset"] = 5
    E.db["unitframe"]["units"]["raid"]["visibility"] = "[@raid6,noexists][@raid26,exists] hide;show"
    -- Raid40
    E.db["unitframe"]["units"]["raid40"]["customTexts"]["!Name"]["attachTextTo"] = "Frame"
    E.db["unitframe"]["units"]["raid40"]["customTexts"]["!Name"]["enable"] = true
    E.db["unitframe"]["units"]["raid40"]["customTexts"]["!Name"]["font"] = "- Big Noodle Titling"
    E.db["unitframe"]["units"]["raid40"]["customTexts"]["!Name"]["fontOutline"] = "NONE"
    E.db["unitframe"]["units"]["raid40"]["customTexts"]["!Name"]["justifyH"] = "CENTER"
    E.db["unitframe"]["units"]["raid40"]["customTexts"]["!Name"]["size"] = 16
    E.db["unitframe"]["units"]["raid40"]["customTexts"]["!Name"]["text_format"] = "[name:short]"
    E.db["unitframe"]["units"]["raid40"]["customTexts"]["!Name"]["xOffset"] = 0
    E.db["unitframe"]["units"]["raid40"]["customTexts"]["!Name"]["yOffset"] = 0
    E.db["unitframe"]["units"]["raid40"]["customTexts"]["!Name"]["fontOutline"] = "OUTLINE"
    E.db["unitframe"]["units"]["raid40"]["width"] = 80
    E.db["unitframe"]["units"]["raid40"]["height"] = 22
    E.db["unitframe"]["units"]["raid40"]["verticalSpacing"] = 1
    E.db["unitframe"]["units"]["raid40"]["horizontalSpacing"] = 1
    E.db["unitframe"]["units"]["raid40"]["groupSpacing"] = 0
    E.db["unitframe"]["units"]["raid40"]["debuffs"]["countFont"] = "- Steelfish"
    E.db["unitframe"]["units"]["raid40"]["groupBy"] = "ROLE"
    E.db["unitframe"]["units"]["raid40"]["groupsPerRowCol"] = 1
    E.db["unitframe"]["units"]["raid40"]["healPrediction"]["absorbStyle"] = "REVERSED"
    E.db["unitframe"]["units"]["raid40"]["healPrediction"]["enable"] = true
    E.db["unitframe"]["units"]["raid40"]["health"]["text_format"] = ""
    E.db["unitframe"]["units"]["raid40"]["name"]["text_format"] = ""
    E.db["unitframe"]["units"]["raid40"]["raidWideSorting"] = false
    E.db["unitframe"]["units"]["raid40"]["startFromCenter"] = false
    E.db["unitframe"]["units"]["raid40"]["rdebuffs"]["duration"]["color"]["b"] = 0.91764705882353
    E.db["unitframe"]["units"]["raid40"]["rdebuffs"]["duration"]["color"]["g"] = 0.94117647058824
    E.db["unitframe"]["units"]["raid40"]["rdebuffs"]["enable"] = true
    E.db["unitframe"]["units"]["raid40"]["rdebuffs"]["font"] = "- Big Noodle Titling"
    E.db["unitframe"]["units"]["raid40"]["rdebuffs"]["fontOutline"] = "OUTLINE"
    E.db["unitframe"]["units"]["raid40"]["rdebuffs"]["fontSize"] = 14
    E.db["unitframe"]["units"]["raid40"]["rdebuffs"]["size"] = 18
    E.db["unitframe"]["units"]["raid40"]["rdebuffs"]["stack"]["color"]["g"] = 0.91372549019608
    E.db["unitframe"]["units"]["raid40"]["rdebuffs"]["stack"]["position"] = "BOTTOMRIGHT"
    E.db["unitframe"]["units"]["raid40"]["rdebuffs"]["stack"]["yOffset"] = 0
    E.db["unitframe"]["units"]["raid40"]["rdebuffs"]["yOffset"] = 4
    E.db["unitframe"]["units"]["raid40"]["rdebuffs"]["xOffset"] = 0
    E.db["unitframe"]["units"]["raid40"]["readycheckIcon"]["size"] = 24
    E.db["unitframe"]["units"]["raid40"]["roleIcon"]["damager"] = false
    E.db["unitframe"]["units"]["raid40"]["roleIcon"]["enable"] = true
    E.db["unitframe"]["units"]["raid40"]["roleIcon"]["position"] = "TOPLEFT"
    E.db["unitframe"]["units"]["raid40"]["roleIcon"]["size"] = 16
    E.db["unitframe"]["units"]["raid40"]["roleIcon"]["xOffset"] = -10
    E.db["unitframe"]["units"]["raid40"]["roleIcon"]["yOffset"] = 5
    E.db["unitframe"]["units"]["raid40"]["visibility"] = "[@raid26,noexists] hide;show"
    -- Main Tank
    E.db["unitframe"]["units"]["tank"]["name"]["text_format"] = "[name:medium]"
    E.db["unitframe"]["units"]["tank"]["targetsGroup"]["name"]["text_format"] = "[name:medium]"
    -- Main Assist
    E.db["unitframe"]["units"]["assist"]["name"]["text_format"] = "[name:medium]"
    E.db["unitframe"]["units"]["assist"]["targetsGroup"]["name"]["text_format"] = "[name:medium]"
    -- Target
    E.db["unitframe"]["units"]["target"]["CombatIcon"]["anchorPoint"] = "LEFT"
    E.db["unitframe"]["units"]["target"]["CombatIcon"]["enable"] = false
    E.db["unitframe"]["units"]["target"]["CombatIcon"]["size"] = 30
    E.db["unitframe"]["units"]["target"]["aurabar"]["enable"] = false
    E.db["unitframe"]["units"]["target"]["aurabar"]["height"] = 26
    E.db["unitframe"]["units"]["target"]["buffs"]["anchorPoint"] = "TOPLEFT"
    E.db["unitframe"]["units"]["target"]["buffs"]["countFont"] = "- Big Noodle Titling"
    E.db["unitframe"]["units"]["target"]["buffs"]["countFontSize"] = 20
    E.db["unitframe"]["units"]["target"]["buffs"]["growthX"] = "RIGHT"
    E.db["unitframe"]["units"]["target"]["buffs"]["perrow"] = 4
    E.db["unitframe"]["units"]["target"]["buffs"]["priority"] = "Blacklist,Personal,Boss,nonPersonal,CastByUnit"
    E.db["unitframe"]["units"]["target"]["buffs"]["sizeOverride"] = 30
    E.db["unitframe"]["units"]["target"]["buffs"]["spacing"] = 0
    E.db["unitframe"]["units"]["target"]["buffs"]["xOffset"] = 3
    E.db["unitframe"]["units"]["target"]["buffs"]["yOffset"] = 25
    E.db["unitframe"]["units"]["target"]["castbar"]["customTextFont"]["enable"] = true
    E.db["unitframe"]["units"]["target"]["castbar"]["customTextFont"]["font"] = "- Big Noodle Titling"
    E.db["unitframe"]["units"]["target"]["castbar"]["customTextFont"]["fontSize"] = 20
    E.db["unitframe"]["units"]["target"]["castbar"]["customTextFont"]["fontStyle"] = "NONE"
    E.db["unitframe"]["units"]["target"]["castbar"]["customTimeFont"]["enable"] = true
    E.db["unitframe"]["units"]["target"]["castbar"]["customTimeFont"]["font"] = "- Big Noodle Titling"
    E.db["unitframe"]["units"]["target"]["castbar"]["customTimeFont"]["fontSize"] = 20
    E.db["unitframe"]["units"]["target"]["castbar"]["customTimeFont"]["fontStyle"] = "NONE"
    E.db["unitframe"]["units"]["target"]["castbar"]["height"] = 25
    E.db["unitframe"]["units"]["target"]["castbar"]["icon"] = false
    E.db["unitframe"]["units"]["target"]["castbar"]["iconAttachedTo"] = "Castbar"
    E.db["unitframe"]["units"]["target"]["castbar"]["insideInfoPanel"] = false
    E.db["unitframe"]["units"]["target"]["castbar"]["textColor"]["b"] = 1
    E.db["unitframe"]["units"]["target"]["castbar"]["textColor"]["g"] = 1
    E.db["unitframe"]["units"]["target"]["castbar"]["textColor"]["r"] = 1
    E.db["unitframe"]["units"]["target"]["castbar"]["width"] = 250
    E.db["unitframe"]["units"]["target"]["castbar"]["xOffsetText"] = 5
    E.db["unitframe"]["units"]["target"]["castbar"]["xOffsetTime"] = -10
    E.db["unitframe"]["units"]["target"]["customTexts"]["!Health"]["attachTextTo"] = "Health"
    E.db["unitframe"]["units"]["target"]["customTexts"]["!Health"]["enable"] = true
    E.db["unitframe"]["units"]["target"]["customTexts"]["!Health"]["font"] = "- Steelfish"
    E.db["unitframe"]["units"]["target"]["customTexts"]["!Health"]["fontOutline"] = "NONE"
    E.db["unitframe"]["units"]["target"]["customTexts"]["!Health"]["justifyH"] = "LEFT"
    E.db["unitframe"]["units"]["target"]["customTexts"]["!Health"]["size"] = 22
    E.db["unitframe"]["units"]["target"]["customTexts"]["!Health"]["text_format"] =
        "[perhp] || [health:current:shortvalue]"
    E.db["unitframe"]["units"]["target"]["customTexts"]["!Health"]["xOffset"] = 10
    E.db["unitframe"]["units"]["target"]["customTexts"]["!Name"]["attachTextTo"] = "Health"
    E.db["unitframe"]["units"]["target"]["customTexts"]["!Name"]["enable"] = true
    E.db["unitframe"]["units"]["target"]["customTexts"]["!Name"]["font"] = "- Big Noodle Titling"
    E.db["unitframe"]["units"]["target"]["customTexts"]["!Name"]["fontOutline"] = "NONE"
    E.db["unitframe"]["units"]["target"]["customTexts"]["!Name"]["justifyH"] = "RIGHT"
    E.db["unitframe"]["units"]["target"]["customTexts"]["!Name"]["size"] = 26
    E.db["unitframe"]["units"]["target"]["customTexts"]["!Name"]["text_format"] = "[name:abbrev:medium]"
    E.db["unitframe"]["units"]["target"]["customTexts"]["!Name"]["xOffset"] = -5
    E.db["unitframe"]["units"]["target"]["customTexts"]["!Power"]["attachTextTo"] = "Power"
    E.db["unitframe"]["units"]["target"]["customTexts"]["!Power"]["enable"] = false
    E.db["unitframe"]["units"]["target"]["customTexts"]["!Power"]["font"] = "Big Noodle Titling"
    E.db["unitframe"]["units"]["target"]["customTexts"]["!Power"]["fontOutline"] = "OUTLINE"
    E.db["unitframe"]["units"]["target"]["customTexts"]["!Power"]["justifyH"] = "CENTER"
    E.db["unitframe"]["units"]["target"]["customTexts"]["!Power"]["size"] = 22
    E.db["unitframe"]["units"]["target"]["customTexts"]["!Power"]["text_format"] = "[perpp]"
    E.db["unitframe"]["units"]["target"]["customTexts"]["!Power"]["xOffset"] = 0
    E.db["unitframe"]["units"]["target"]["customTexts"]["!Power"]["yOffset"] = 5
    E.db["unitframe"]["units"]["target"]["customTexts"]["!rare"]["attachTextTo"] = "Health"
    E.db["unitframe"]["units"]["target"]["customTexts"]["!rare"]["enable"] = false
    E.db["unitframe"]["units"]["target"]["customTexts"]["!rare"]["font"] = "Big Noodle Titling"
    E.db["unitframe"]["units"]["target"]["customTexts"]["!rare"]["fontOutline"] = "OUTLINE"
    E.db["unitframe"]["units"]["target"]["customTexts"]["!rare"]["justifyH"] = "RIGHT"
    E.db["unitframe"]["units"]["target"]["customTexts"]["!rare"]["size"] = 18
    E.db["unitframe"]["units"]["target"]["customTexts"]["!rare"]["text_format"] = "[rare]"
    E.db["unitframe"]["units"]["target"]["customTexts"]["!rare"]["xOffset"] = -5
    E.db["unitframe"]["units"]["target"]["customTexts"]["!rare"]["yOffset"] = 0
    E.db["unitframe"]["units"]["target"]["debuffs"]["anchorPoint"] = "TOPRIGHT"
    E.db["unitframe"]["units"]["target"]["debuffs"]["attachTo"] = "FRAME"
    E.db["unitframe"]["units"]["target"]["debuffs"]["countFont"] = "- Big Noodle Titling"
    E.db["unitframe"]["units"]["target"]["debuffs"]["countFontSize"] = 20
    E.db["unitframe"]["units"]["target"]["debuffs"]["durationPosition"] = "TOP"
    E.db["unitframe"]["units"]["target"]["debuffs"]["maxDuration"] = 0
    E.db["unitframe"]["units"]["target"]["debuffs"]["perrow"] = 4
    E.db["unitframe"]["units"]["target"]["debuffs"]["priority"] =
        "Blacklist,Boss,Personal,RaidDebuffs,CastByUnit,CCDebuffs"
    E.db["unitframe"]["units"]["target"]["debuffs"]["sizeOverride"] = 30
    E.db["unitframe"]["units"]["target"]["debuffs"]["spacing"] = 0
    E.db["unitframe"]["units"]["target"]["debuffs"]["xOffset"] = -3
    E.db["unitframe"]["units"]["target"]["debuffs"]["yOffset"] = 25
    E.db["unitframe"]["units"]["target"]["disableMouseoverGlow"] = true
    E.db["unitframe"]["units"]["target"]["fader"]["enable"] = false
    E.db["unitframe"]["units"]["target"]["fader"]["minAlpha"] = 0.3
    E.db["unitframe"]["units"]["target"]["fader"]["range"] = true
    E.db["unitframe"]["units"]["target"]["healPrediction"]["absorbStyle"] = "REVERSED"
    E.db["unitframe"]["units"]["target"]["health"]["attachTextTo"] = "InfoPanel"
    E.db["unitframe"]["units"]["target"]["health"]["position"] = "LEFT"
    E.db["unitframe"]["units"]["target"]["health"]["text_format"] = ""
    E.db["unitframe"]["units"]["target"]["health"]["xOffset"] = 2
    E.db["unitframe"]["units"]["target"]["name"]["text_format"] = ""
    E.db["unitframe"]["units"]["target"]["orientation"] = "LEFT"
    E.db["unitframe"]["units"]["target"]["portrait"]["fullOverlay"] = true
    E.db["unitframe"]["units"]["target"]["portrait"]["overlay"] = true
    E.db["unitframe"]["units"]["target"]["portrait"]["overlayAlpha"] = 0.25
    E.db["unitframe"]["units"]["target"]["portrait"]["rotation"] = 320
    E.db["unitframe"]["units"]["target"]["portrait"]["xOffset"] = 0.3
    E.db["unitframe"]["units"]["target"]["power"]["attachTextTo"] = "Power"
    E.db["unitframe"]["units"]["target"]["power"]["detachFromFrame"] = true
    E.db["unitframe"]["units"]["target"]["power"]["detachedWidth"] = 120
    E.db["unitframe"]["units"]["target"]["power"]["position"] = "RIGHT"
    E.db["unitframe"]["units"]["target"]["power"]["strataAndLevel"]["frameLevel"] = 82
    E.db["unitframe"]["units"]["target"]["power"]["strataAndLevel"]["frameStrata"] = "MEDIUM"
    E.db["unitframe"]["units"]["target"]["power"]["strataAndLevel"]["useCustomStrata"] = true
    E.db["unitframe"]["units"]["target"]["power"]["text_format"] = ""
    E.db["unitframe"]["units"]["target"]["power"]["xOffset"] = -2
    E.db["unitframe"]["units"]["target"]["power"]["enable"] = false
    E.db["unitframe"]["units"]["target"]["raidicon"]["attachTo"] = "CENTER"
    E.db["unitframe"]["units"]["target"]["raidicon"]["size"] = 24
    E.db["unitframe"]["units"]["target"]["raidicon"]["yOffset"] = 0
    E.db["unitframe"]["units"]["target"]["width"] = 250
    -- Target Target
    E.db["unitframe"]["units"]["targettarget"]["customTexts"]["!Name"]["attachTextTo"] = "Health"
    E.db["unitframe"]["units"]["targettarget"]["customTexts"]["!Name"]["enable"] = true
    E.db["unitframe"]["units"]["targettarget"]["customTexts"]["!Name"]["font"] = "- Big Noodle Titling"
    E.db["unitframe"]["units"]["targettarget"]["customTexts"]["!Name"]["fontOutline"] = "NONE"
    E.db["unitframe"]["units"]["targettarget"]["customTexts"]["!Name"]["justifyH"] = "CENTER"
    E.db["unitframe"]["units"]["targettarget"]["customTexts"]["!Name"]["size"] = 16
    E.db["unitframe"]["units"]["targettarget"]["customTexts"]["!Name"]["text_format"] = "[name:short]"
    E.db["unitframe"]["units"]["targettarget"]["customTexts"]["!Name"]["xOffset"] = 0
    E.db["unitframe"]["units"]["targettarget"]["debuffs"]["anchorPoint"] = "TOPRIGHT"
    E.db["unitframe"]["units"]["targettarget"]["debuffs"]["enable"] = false
    E.db["unitframe"]["units"]["targettarget"]["disableMouseoverGlow"] = true
    E.db["unitframe"]["units"]["targettarget"]["name"]["text_format"] = ""
    E.db["unitframe"]["units"]["targettarget"]["power"]["enable"] = false
    E.db["unitframe"]["units"]["targettarget"]["raidicon"]["attachTo"] = "CENTER"
    E.db["unitframe"]["units"]["targettarget"]["raidicon"]["size"] = 16
    E.db["unitframe"]["units"]["targettarget"]["raidicon"]["yOffset"] = 0
    E.db["unitframe"]["units"]["targettarget"]["threatStyle"] = "GLOW"
    E.db["unitframe"]["units"]["targettarget"]["width"] = 100

    -- DataTexts
    for _, v in pairs(E.db.datatexts.panels) do if (type(v) == "table") then v.enable = false end end

    -- ActionBars
    E.db["actionbar"]["transparent"] = true
    E.db["actionbar"]["bar1"]["enabled"] = true
    E.db["actionbar"]["bar1"]["buttonSize"] = 30
    E.db["actionbar"]["bar1"]["buttonsPerRow"] = 6
    E.db["actionbar"]["bar1"]["countFont"] = "- Big Noodle Titling"
    E.db["actionbar"]["bar1"]["countFontOutline"] = "OUTLINE"
    E.db["actionbar"]["bar1"]["countFontSize"] = 16
    E.db["actionbar"]["bar1"]["hotkeyFont"] = "- Big Noodle Titling"
    E.db["actionbar"]["bar1"]["hotkeyFontOutline"] = "OUTLINE"
    E.db["actionbar"]["bar1"]["hotkeyFontSize"] = 16
    E.db["actionbar"]["bar1"]["hotkeyTextYOffset"] = 0
    E.db["actionbar"]["bar1"]["inheritGlobalFade"] = true
    E.db["actionbar"]["bar1"]["macroFont"] = "- Big Noodle Titling"
    E.db["actionbar"]["bar1"]["macroFontOutline"] = "OUTLINE"
    E.db["actionbar"]["bar1"]["macroFontSize"] = 12
    E.db["actionbar"]["bar1"]["macroTextPosition"] = "BOTTOM"
    E.db["actionbar"]["bar1"]["macroTextYOffset"] = 0
    E.db["actionbar"]["bar1"]["macrotext"] = true
    E.db["actionbar"]["bar1"]["point"] = "TOPLEFT"
    E.db["actionbar"]["bar1"]["counttext"] = true
    E.db["actionbar"]["bar1"]["hotkeytext"] = true
    E.db["actionbar"]["bar1"]["hotkeyTextPosition"] = "TOPRIGHT"
    E.db["actionbar"]["bar1"]["countTextPosition"] = "BOTTOMLEFT"
    E.db["actionbar"]["bar2"]["enabled"] = false
    E.db["actionbar"]["bar2"]["buttons"] = 12
    E.db["actionbar"]["bar2"]["buttonsPerRow"] = 1
    E.db["actionbar"]["bar2"]["countFont"] = "- Big Noodle Titling"
    E.db["actionbar"]["bar2"]["countFontOutline"] = "OUTLINE"
    E.db["actionbar"]["bar2"]["countFontSize"] = 16
    E.db["actionbar"]["bar2"]["hotkeyFont"] = "- Big Noodle Titling"
    E.db["actionbar"]["bar2"]["hotkeyFontOutline"] = "OUTLINE"
    E.db["actionbar"]["bar2"]["hotkeyFontSize"] = 16
    E.db["actionbar"]["bar2"]["hotkeyTextYOffset"] = 0
    E.db["actionbar"]["bar2"]["macroFont"] = "- Big Noodle Titling"
    E.db["actionbar"]["bar2"]["macroFontOutline"] = "OUTLINE"
    E.db["actionbar"]["bar2"]["macroFontSize"] = 16
    E.db["actionbar"]["bar2"]["counttext"] = true
    E.db["actionbar"]["bar2"]["hotkeytext"] = true
    E.db["actionbar"]["bar2"]["hotkeyTextPosition"] = "TOPRIGHT"
    E.db["actionbar"]["bar2"]["countTextPosition"] = "BOTTOMLEFT"
    E.db["actionbar"]["bar3"]["enabled"] = true
    E.db["actionbar"]["bar3"]["buttons"] = 9
    E.db["actionbar"]["bar3"]["buttonSize"] = 30
    E.db["actionbar"]["bar3"]["buttonsPerRow"] = 3
    E.db["actionbar"]["bar3"]["countFont"] = "- Big Noodle Titling"
    E.db["actionbar"]["bar3"]["countFontOutline"] = "OUTLINE"
    E.db["actionbar"]["bar3"]["countFontSize"] = 16
    E.db["actionbar"]["bar3"]["hotkeyFont"] = "- Big Noodle Titling"
    E.db["actionbar"]["bar3"]["hotkeyFontOutline"] = "OUTLINE"
    E.db["actionbar"]["bar3"]["hotkeyFontSize"] = 16
    E.db["actionbar"]["bar3"]["hotkeyTextYOffset"] = 0
    E.db["actionbar"]["bar3"]["inheritGlobalFade"] = true
    E.db["actionbar"]["bar3"]["macroFont"] = "- Big Noodle Titling"
    E.db["actionbar"]["bar3"]["macroFontOutline"] = "OUTLINE"
    E.db["actionbar"]["bar3"]["macroFontSize"] = 16
    E.db["actionbar"]["bar3"]["showGrid"] = false
    E.db["actionbar"]["bar3"]["visibility"] = "[petbattle] hide; show"
    E.db["actionbar"]["bar3"]["counttext"] = true
    E.db["actionbar"]["bar3"]["hotkeytext"] = true
    E.db["actionbar"]["bar3"]["hotkeyTextPosition"] = "TOPRIGHT"
    E.db["actionbar"]["bar3"]["countTextPosition"] = "BOTTOMLEFT"
    E.db["actionbar"]["bar4"]["enabled"] = true
    E.db["actionbar"]["bar4"]["backdrop"] = false
    E.db["actionbar"]["bar4"]["buttons"] = 9
    E.db["actionbar"]["bar4"]["buttonSize"] = 30
    E.db["actionbar"]["bar4"]["buttonsPerRow"] = 3
    E.db["actionbar"]["bar4"]["countFont"] = "- Big Noodle Titling"
    E.db["actionbar"]["bar4"]["countFontOutline"] = "OUTLINE"
    E.db["actionbar"]["bar4"]["countFontSize"] = 16
    E.db["actionbar"]["bar4"]["hotkeyFont"] = "- Big Noodle Titling"
    E.db["actionbar"]["bar4"]["hotkeyFontOutline"] = "OUTLINE"
    E.db["actionbar"]["bar4"]["hotkeyFontSize"] = 16
    E.db["actionbar"]["bar4"]["hotkeyTextYOffset"] = 0
    E.db["actionbar"]["bar4"]["inheritGlobalFade"] = true
    E.db["actionbar"]["bar4"]["macroFont"] = "- Big Noodle Titling"
    E.db["actionbar"]["bar4"]["macroFontOutline"] = "OUTLINE"
    E.db["actionbar"]["bar4"]["macroFontSize"] = 16
    E.db["actionbar"]["bar4"]["point"] = "TOPLEFT"
    E.db["actionbar"]["bar4"]["showGrid"] = false
    E.db["actionbar"]["bar4"]["visibility"] = "[petbattle] hide; show"
    E.db["actionbar"]["bar4"]["counttext"] = true
    E.db["actionbar"]["bar4"]["hotkeytext"] = true
    E.db["actionbar"]["bar4"]["hotkeyTextPosition"] = "TOPRIGHT"
    E.db["actionbar"]["bar4"]["countTextPosition"] = "BOTTOMLEFT"
    E.db["actionbar"]["bar5"]["enabled"] = true
    E.db["actionbar"]["bar5"]["buttons"] = 12
    E.db["actionbar"]["bar5"]["buttonSize"] = 30
    E.db["actionbar"]["bar5"]["buttonsPerRow"] = 6
    E.db["actionbar"]["bar5"]["countFont"] = "- Big Noodle Titling"
    E.db["actionbar"]["bar5"]["countFontOutline"] = "OUTLINE"
    E.db["actionbar"]["bar5"]["countFontSize"] = 16
    E.db["actionbar"]["bar5"]["hotkeyFont"] = "- Big Noodle Titling"
    E.db["actionbar"]["bar5"]["hotkeyFontOutline"] = "OUTLINE"
    E.db["actionbar"]["bar5"]["hotkeyFontSize"] = 16
    E.db["actionbar"]["bar5"]["hotkeyTextYOffset"] = 0
    E.db["actionbar"]["bar5"]["inheritGlobalFade"] = true
    E.db["actionbar"]["bar5"]["macroFont"] = "- Big Noodle Titling"
    E.db["actionbar"]["bar5"]["macroFontOutline"] = "OUTLINE"
    E.db["actionbar"]["bar5"]["macroFontSize"] = 16
    E.db["actionbar"]["bar5"]["point"] = "TOPLEFT"
    E.db["actionbar"]["bar5"]["visibility"] = "[petbattle] hide; show"
    E.db["actionbar"]["bar5"]["counttext"] = true
    E.db["actionbar"]["bar5"]["hotkeytext"] = true
    E.db["actionbar"]["bar5"]["hotkeyTextPosition"] = "TOPRIGHT"
    E.db["actionbar"]["bar5"]["countTextPosition"] = "BOTTOMLEFT"
    E.db["actionbar"]["bar6"]["enabled"] = true
    E.db["actionbar"]["bar6"]["buttons"] = 12
    E.db["actionbar"]["bar6"]["buttonSize"] = 30
    E.db["actionbar"]["bar6"]["buttonsPerRow"] = 6
    E.db["actionbar"]["bar6"]["countFont"] = "- Big Noodle Titling"
    E.db["actionbar"]["bar6"]["countFontOutline"] = "OUTLINE"
    E.db["actionbar"]["bar6"]["countFontSize"] = 16
    E.db["actionbar"]["bar6"]["hotkeyFont"] = "- Big Noodle Titling"
    E.db["actionbar"]["bar6"]["hotkeyFontOutline"] = "OUTLINE"
    E.db["actionbar"]["bar6"]["hotkeyFontSize"] = 16
    E.db["actionbar"]["bar6"]["hotkeyTextYOffset"] = 0
    E.db["actionbar"]["bar6"]["inheritGlobalFade"] = true
    E.db["actionbar"]["bar6"]["macroFont"] = "- Big Noodle Titling"
    E.db["actionbar"]["bar6"]["macroFontOutline"] = "OUTLINE"
    E.db["actionbar"]["bar6"]["macroFontSize"] = 16
    E.db["actionbar"]["bar6"]["point"] = "TOPLEFT"
    E.db["actionbar"]["bar6"]["visibility"] = "[petbattle] hide; show"
    E.db["actionbar"]["bar6"]["counttext"] = true
    E.db["actionbar"]["bar6"]["hotkeytext"] = true
    E.db["actionbar"]["bar6"]["hotkeyTextPosition"] = "TOPRIGHT"
    E.db["actionbar"]["bar6"]["countTextPosition"] = "BOTTOMLEFT"
    E.db["actionbar"]["bar7"]["enabled"] = false
    E.db["actionbar"]["bar7"]["buttonsPerRow"] = 1
    E.db["actionbar"]["bar7"]["countFont"] = "- Big Noodle Titling"
    E.db["actionbar"]["bar7"]["countFontOutline"] = "OUTLINE"
    E.db["actionbar"]["bar7"]["countFontSize"] = 16
    E.db["actionbar"]["bar7"]["hotkeyFont"] = "- Big Noodle Titling"
    E.db["actionbar"]["bar7"]["hotkeyFontOutline"] = "OUTLINE"
    E.db["actionbar"]["bar7"]["hotkeyFontSize"] = 16
    E.db["actionbar"]["bar7"]["hotkeyTextYOffset"] = 0
    E.db["actionbar"]["bar7"]["macroFont"] = "- Big Noodle Titling"
    E.db["actionbar"]["bar7"]["macroFontOutline"] = "OUTLINE"
    E.db["actionbar"]["bar7"]["macroFontSize"] = 16
    E.db["actionbar"]["bar7"]["counttext"] = true
    E.db["actionbar"]["bar7"]["hotkeytext"] = true
    E.db["actionbar"]["bar7"]["hotkeyTextPosition"] = "TOPRIGHT"
    E.db["actionbar"]["bar7"]["countTextPosition"] = "BOTTOMLEFT"
    E.db["actionbar"]["bar8"]["enabled"] = false
    E.db["actionbar"]["bar8"]["buttonsPerRow"] = 1
    E.db["actionbar"]["bar8"]["countFont"] = "- Big Noodle Titling"
    E.db["actionbar"]["bar8"]["countFontOutline"] = "OUTLINE"
    E.db["actionbar"]["bar8"]["countFontSize"] = 16
    E.db["actionbar"]["bar8"]["hotkeyFont"] = "- Big Noodle Titling"
    E.db["actionbar"]["bar8"]["hotkeyFontOutline"] = "OUTLINE"
    E.db["actionbar"]["bar8"]["hotkeyFontSize"] = 16
    E.db["actionbar"]["bar8"]["hotkeyTextYOffset"] = 0
    E.db["actionbar"]["bar8"]["macroFont"] = "- Big Noodle Titling"
    E.db["actionbar"]["bar8"]["macroFontOutline"] = "OUTLINE"
    E.db["actionbar"]["bar8"]["macroFontSize"] = 16
    E.db["actionbar"]["bar8"]["counttext"] = true
    E.db["actionbar"]["bar8"]["hotkeytext"] = true
    E.db["actionbar"]["bar8"]["hotkeyTextPosition"] = "TOPRIGHT"
    E.db["actionbar"]["bar8"]["countTextPosition"] = "BOTTOMLEFT"
    E.db["actionbar"]["bar9"]["enabled"] = false
    E.db["actionbar"]["bar9"]["buttonsPerRow"] = 1
    E.db["actionbar"]["bar9"]["countFont"] = "- Big Noodle Titling"
    E.db["actionbar"]["bar9"]["countFontOutline"] = "OUTLINE"
    E.db["actionbar"]["bar9"]["countFontSize"] = 16
    E.db["actionbar"]["bar9"]["hotkeyFont"] = "- Big Noodle Titling"
    E.db["actionbar"]["bar9"]["hotkeyFontOutline"] = "OUTLINE"
    E.db["actionbar"]["bar9"]["hotkeyFontSize"] = 16
    E.db["actionbar"]["bar9"]["hotkeyTextYOffset"] = 0
    E.db["actionbar"]["bar9"]["macroFont"] = "- Big Noodle Titling"
    E.db["actionbar"]["bar9"]["macroFontOutline"] = "OUTLINE"
    E.db["actionbar"]["bar9"]["macroFontSize"] = 16
    E.db["actionbar"]["bar9"]["counttext"] = true
    E.db["actionbar"]["bar9"]["hotkeytext"] = true
    E.db["actionbar"]["bar9"]["hotkeyTextPosition"] = "TOPRIGHT"
    E.db["actionbar"]["bar9"]["countTextPosition"] = "BOTTOMLEFT"
    E.db["actionbar"]["bar10"]["enabled"] = false
    E.db["actionbar"]["bar10"]["buttonsPerRow"] = 1
    E.db["actionbar"]["bar10"]["countFont"] = "- Big Noodle Titling"
    E.db["actionbar"]["bar10"]["countFontOutline"] = "OUTLINE"
    E.db["actionbar"]["bar10"]["countFontSize"] = 16
    E.db["actionbar"]["bar10"]["hotkeyFont"] = "- Big Noodle Titling"
    E.db["actionbar"]["bar10"]["hotkeyFontOutline"] = "OUTLINE"
    E.db["actionbar"]["bar10"]["hotkeyFontSize"] = 16
    E.db["actionbar"]["bar10"]["hotkeyTextYOffset"] = 0
    E.db["actionbar"]["bar10"]["macroFont"] = "- Big Noodle Titling"
    E.db["actionbar"]["bar10"]["macroFontOutline"] = "OUTLINE"
    E.db["actionbar"]["bar10"]["macroFontSize"] = 16
    E.db["actionbar"]["bar10"]["counttext"] = true
    E.db["actionbar"]["bar10"]["hotkeytext"] = true
    E.db["actionbar"]["bar10"]["hotkeyTextPosition"] = "TOPRIGHT"
    E.db["actionbar"]["bar10"]["countTextPosition"] = "BOTTOMLEFT"
    E.db["actionbar"]["barPet"]["backdrop"] = false
    E.db["actionbar"]["barPet"]["backdropSpacing"] = 1
    E.db["actionbar"]["barPet"]["buttonSize"] = 20
    E.db["actionbar"]["barPet"]["buttonSpacing"] = 1
    E.db["actionbar"]["barPet"]["buttonsPerRow"] = 10
    E.db["actionbar"]["barPet"]["countFontSize"] = 38
    E.db["actionbar"]["barPet"]["hotkeyFont"] = "- Big Noodle Titling"
    E.db["actionbar"]["barPet"]["hotkeyFontOutline"] = "OUTLINE"
    E.db["actionbar"]["barPet"]["hotkeyFontSize"] = 16
    E.db["actionbar"]["barPet"]["hotkeyTextPosition"] = "TOPLEFT"
    E.db["actionbar"]["barPet"]["hotkeyTextXOffset"] = 2
    E.db["actionbar"]["barPet"]["hotkeyTextYOffset"] = -2
    E.db["actionbar"]["barPet"]["mouseover"] = true
    E.db["actionbar"]["cooldown"]["checkSeconds"] = true
    E.db["actionbar"]["cooldown"]["fonts"]["enable"] = true
    E.db["actionbar"]["cooldown"]["fonts"]["font"] = "- Steelfish"
    E.db["actionbar"]["cooldown"]["hhmmThreshold"] = 11
    E.db["actionbar"]["cooldown"]["mmssThreshold"] = 300
    E.db["actionbar"]["countTextYOffset"] = 0
    E.db["actionbar"]["extraActionButton"]["scale"] = 1.25
    E.db["actionbar"]["flyoutSize"] = 33
    E.db["actionbar"]["font"] = "- Big Noodle Titling"
    E.db["actionbar"]["fontOutline"] = "OUTLINE"
    E.db["actionbar"]["fontSize"] = 16
    E.db["actionbar"]["globalFadeAlpha"] = 1
    E.db["actionbar"]["stanceBar"]["alpha"] = 0.8
    E.db["actionbar"]["stanceBar"]["buttonSize"] = 20
    E.db["actionbar"]["stanceBar"]["hotkeyFont"] = "- Big Noodle Titling"
    E.db["actionbar"]["stanceBar"]["hotkeyFontOutline"] = "OUTLINE"
    E.db["actionbar"]["stanceBar"]["hotkeyFontSize"] = 16
    E.db["actionbar"]["stanceBar"]["hotkeyTextPosition"] = "TOP"
    E.db["actionbar"]["stanceBar"]["inheritGlobalFade"] = true
    E.db["actionbar"]["stanceBar"]["mouseover"] = true
    E.db["actionbar"]["zoneActionButton"]["scale"] = 1.25

    -- General
    E.db["general"]["afk"] = true
    E.db["general"]["altPowerBar"]["font"] = "- Big Noodle Titling"
    E.db["general"]["altPowerBar"]["fontSize"] = 16
    E.db["general"]["autoRepair"] = "PLAYER"
    E.db["general"]["backdropcolor"]["b"] = 0.10196078431373
    E.db["general"]["backdropcolor"]["g"] = 0.10196078431373
    E.db["general"]["backdropcolor"]["r"] = 0.10196078431373
    E.db["general"]["backdropfadecolor"]["a"] = 0.80000001192093
    E.db["general"]["backdropfadecolor"]["b"] = 0.16078431372549
    E.db["general"]["backdropfadecolor"]["g"] = 0.16078431372549
    E.db["general"]["backdropfadecolor"]["r"] = 0.16078431372549
    E.db["general"]["bottomPanel"] = false
    E.db["general"]["fontStyle"] = "NONE"
    E.db["general"]["itemLevel"]["itemLevelFontOutline"] = "NONE"
    E.db["general"]["itemLevel"]["itemLevelFontSize"] = 14
    E.db["general"]["minimap"]["icons"]["lfgEye"]["xOffset"] = 0
    E.db["general"]["minimap"]["icons"]["mail"]["xOffset"] = 0
    E.db["general"]["minimap"]["icons"]["mail"]["yOffset"] = 0
    E.db["general"]["minimap"]["locationFont"] = "- Big Noodle Titling"
    E.db["general"]["minimap"]["locationFontSize"] = 20
    E.db["general"]["minimap"]["size"] = 230
    E.db["general"]["objectiveFrameAutoHideInKeystone"] = true
    E.db["general"]["objectiveFrameHeight"] = 500
    E.db["general"]["resurrectSound"] = true
    E.db["general"]["stickyFrames"] = false
    E.db["general"]["talkingHeadFrameBackdrop"] = true
    E.db["general"]["talkingHeadFrameScale"] = 1
    E.db["general"]["totems"]["growthDirection"] = "HORIZONTAL"
    E.db["general"]["totems"]["size"] = 50
    E.db["general"]["totems"]["spacing"] = 8
    E.db["general"]["valuecolor"]["b"] = 1
    E.db["general"]["valuecolor"]["g"] = 1
    E.db["general"]["valuecolor"]["r"] = 1
    E.db["cooldown"]["checkSeconds"] = true
    E.db["cooldown"]["fonts"]["enable"] = true
    E.db["cooldown"]["fonts"]["font"] = "- Steelfish"
    E.db["cooldown"]["fonts"]["fontSize"] = 20
    E.db["cooldown"]["minutesColor"]["b"] = 0.95294117647059
    E.db["cooldown"]["minutesColor"]["r"] = 0.16470588235294
    E.db["cooldown"]["mmssColor"]["b"] = 0.49411764705882
    E.db["cooldown"]["mmssColor"]["g"] = 1
    E.db["cooldown"]["mmssColor"]["r"] = 0
    E.db["cooldown"]["mmssThreshold"] = 300
    E.db["cooldown"]["secondsColor"]["b"] = 1
    E.db["cooldown"]["threshold"] = -1

    -- Global
    E.global["uiScaleInformed"] = true
    E.global["general"]["commandBarSetting"] = "DISABLED"
    E.global["general"]["UIScale"] = 0.64

    -- ! IMPORTANT ! --
    E.db["actionbar"]["convertPages"] = false -- just don't !
    E.db["convertPages"] = true -- don't you dare fuck the action bars up again
    E.db["general"]["taintLog"] = false
end

function PF:ElvUIProfilePrivate()
    -- General
    E.private["general"]["chatBubbleFontSize"] = 18
    E.private["general"]["chatBubbles"] = "nobackdrop"
    E.private["general"]["raidUtility"] = true
    E.private["general"]["totemBar"] = false
    E.private["general"]["minimap"]["hideClassHallReport"] = false
    E.private["general"]["glossTex"] = "- ToxiUI" -- Secondary Texture

    -- NamePlates ElvUI
    E.private["nameplates"]["enable"] = false

    -- Chat
    E.private["chat"]["enable"] = true

    -- Skins
    E.private["skins"]["parchmentRemoverEnable"] = true
end
